README.md
Changed the description so it's clear it's a work in progress.
Kept the releases section, but commented out the previous text (which we'll need later) and instead state there are no releases, but this will be updated in the future.
=> Reworked description and release sections of the README

.github/workflows/build-doxygen-docs.yml, .gitmodules, CMakeLists.txt, docs/footer.html, docs/header.html, include/cubos/gl/render_device.hpp, include/cubos/io/window.hpp, include/cubos/log.hpp, shell.nix
=> Configured doxygen and fixed docs

.github/workflows/build-doxygen-docs.yml
Removed on PR trigger.
There's no use in building the documentation in the PRs, we should only do it when there's a change in the main branch.
=> Doxygen workflow fixes

src/gl/ogl_render_device.cpp
=> Fixed OpenGL error 1281 on OGLShaderPipeline::getBindingPoint()

include/cubos/event.hpp, include/cubos/gl/ogl_render_device.hpp, include/cubos/gl/render_device.hpp, include/cubos/io/keyboard.hpp, include/cubos/io/window.hpp, include/cubos/log.hpp, include/cubos/settings.hpp
=> Added periods to the end of documentation comments

core/CMakeLists.txt, core/include/cubos/gl/grid.hpp, core/include/cubos/gl/material.hpp, core/include/cubos/gl/palette.hpp, core/src/cubos/gl/grid.cpp, core/src/cubos/gl/material.cpp, core/src/cubos/gl/palette.cpp
=> Defined gl::Material, gl::Palette and gl::Grid

.github/workflows/build-engine-linux.yml, .github/workflows/build-engine-windows.yml
=> Creating a Github Action to build the engine on windows

core/include/cubos/event.hpp
Besides static methods, it should be possible to register methods.
=> Add object callbacks to Events

core/CMakeLists.txt, core/include/cubos/gl/render_device.hpp, core/include/cubos/gl/util.hpp, core/src/cubos/gl/util.cpp
=> Add getScreenQuad method

core/include/cubos/gl/grid.hpp, core/include/cubos/gl/palette.hpp, core/src/cubos/gl/grid.cpp, core/src/cubos/gl/palette.cpp
=> Simplify grid & palette (remove 8-bit indices)

core/include/cubos/settings.hpp, core/src/cubos/settings.cpp, core/tests/test_settings.cpp
=> Add Global Settings with Serialization

core/include/cubos/memory/stream.hpp, core/src/cubos/memory/stream.cpp
=> Fix type ambiguity on Stream::print functions

CONTRIBUTE.md, README.md
=> Enhance README.md

core/include/cubos/core/gl/grid.hpp, core/src/cubos/core/gl/grid.cpp, engine/CMakeLists.txt, engine/include/cubos/engine/data/asset_manager.hpp, engine/include/cubos/engine/data/grid.hpp, engine/include/cubos/engine/data/loader.hpp, engine/include/cubos/engine/data/qb_model.hpp, engine/samples/asset.cpp, engine/src/cubos/engine/data/grid.cpp, engine/src/cubos/engine/data/loader.cpp
Add Asset Manager argument to Loaders
=> Add Grid Asset and Loader

CMakeLists.txt, README.md, docs/1_core.md, docs/2_engine.md, docs/3_cubinhos.md, docs/main.md, tools/src/convert.cpp
- Adds an introduction page to Doxygen docs
- Adds a guide explaining how to use Cubinhos
- Fixed a nitpick in the `cubinhos convert` behaviour.
=> Add introduction and Cubinhos guide to docs

core/include/cubos/core/ecs/world.hpp
Fixes a compile error occurring on my setup regarding `ssize_t`
=> Fix compile error

core/include/cubos/core/ecs/component_manager.hpp, core/include/cubos/core/ecs/query.hpp, engine/include/cubos/engine/cubos.hpp, engine/samples/empty.cpp, engine/samples/scene.cpp, engine/src/cubos/engine/cubos.cpp
Initial implementation of the Cubos class, which will manage many low-level aspects of the engine so the user doesn't have to worry about them.
I had to add some random includes to make it compile on my setup.
Closes #192
=> Add Cubos main class

core/include/cubos/core/settings.hpp, core/src/cubos/core/settings.cpp, core/tests/test_settings.cpp, engine/include/cubos/engine/gl/deferred/renderer.hpp, engine/samples/asset_renderer.cpp, engine/samples/bloom.cpp, engine/samples/cars.cpp, engine/samples/renderer.cpp, engine/samples/ssao.cpp, engine/src/cubos/engine/gl/deferred/renderer.cpp
Closes #217
The settings 'global' singleton is no longer necessary since it will now be used as a Resource.
=> Remove Settings singleton

core/src/cubos/core/ecs/dispatcher.cpp, engine/CMakeLists.txt, engine/include/cubos/engine/cubos.hpp, engine/include/cubos/engine/plugins/window.hpp, engine/samples/assets/scenes/main.cubos, engine/samples/scene.cpp, engine/src/cubos/engine/cubos.cpp, engine/src/cubos/engine/gl/deferred/renderer.cpp, engine/src/cubos/engine/plugins/window.cpp, tools/src/convert.cpp, tools/src/embed.cpp, tools/src/generate.cpp
Depends on #242
Fixed a wrong struct parameter that was causing a crash on start-up
=> Fix index buffer segfault

core/CMakeLists.txt, core/include/cubos/core/thread_pool.hpp, core/src/cubos/core/thread_pool.cpp, core/tests/CMakeLists.txt, core/tests/test_thread_pool.cpp
=> Add ThreadPool and tests for it

core/src/cubos/core/data/file_system.cpp, engine/samples/scene/main.cpp, engine/src/cubos/engine/plugins/file_settings.cpp
Added some stuff that was missing from #283 and fixed merge errors that made the scene sample fail to execute.
=> File settings plugin fix

.github/workflows/build-engine-macos.yml, core/include/cubos/core/data/json_serializer.hpp, core/include/cubos/core/ecs/event_pipe.hpp, core/include/cubos/core/ecs/event_reader.hpp, core/include/cubos/core/ecs/event_writer.hpp, core/include/cubos/core/thread_pool.hpp, core/src/cubos/core/memory/stream.cpp, engine/include/cubos/engine/cubos.hpp, engine/src/cubos/engine/cubos.cpp, test.cpp, tools/cubinhos/src/convert.cpp, tools/cubinhos/src/embed.cpp, tools/cubinhos/src/generate.cpp
Hopefully it fixes the current issues and generates less problems from now on.
Closes #293
=> Switch macOS CI to use LLVM/clang

core/src/cubos/core/io/glfw_window.cpp
Use the appropriate callback to handle GLFW errors
=> Improve GLFW errors

core/src/cubos/core/al/oal_audio_device.cpp
=> Respect WITH_OPENAL

.github/workflows/build-engine-linux.yml, .github/workflows/build-engine-macos.yml, .github/workflows/build-engine-windows.yml
=> Activate building of engine samples on CI

core/CMakeLists.txt, core/lib/stduuid/uuid.h
=> Add `stduuid` to core

core/CMakeLists.txt, core/include/cubos/core/ecs/dispatcher.hpp, core/src/cubos/core/ecs/dispatcher.cpp, engine/include/cubos/engine/cubos.hpp, engine/samples/systems/main.cpp
Implement conditions that control system/tag execution.
Closes #290
=> Implement conditions on dispatcher

engine/CMakeLists.txt, engine/include/cubos/engine/tools/world_inspector/plugin.hpp, engine/samples/scene/main.cpp, engine/src/cubos/engine/tools/world_inspector/plugin.cpp
=> Add World Inspector

engine/CMakeLists.txt, engine/include/cubos/engine/tools/entity_inspector/plugin.hpp, engine/samples/scene/main.cpp, engine/src/cubos/engine/tools/entity_inspector/plugin.cpp
closes #264 .
Name of the inspector got changed.
=> Add Entity Inspector

CMakeLists.txt, core/include/cubos/core/data/package.hpp, core/include/cubos/core/ecs/blueprint.hpp, core/include/cubos/core/ecs/commands.hpp, core/include/cubos/core/ecs/component_manager.hpp, core/include/cubos/core/ecs/entity_manager.hpp, core/include/cubos/core/ecs/query.hpp, core/include/cubos/core/ecs/storage.hpp, core/include/cubos/core/ecs/vec_storage.hpp, core/include/cubos/core/ecs/world.hpp, core/include/cubos/core/memory/stream.hpp, core/include/cubos/core/ui/ecs.hpp, core/src/cubos/core/data/package.cpp, core/src/cubos/core/ecs/component_manager.cpp, core/src/cubos/core/ecs/entity_manager.cpp, core/src/cubos/core/ecs/registry.cpp, core/src/cubos/core/ecs/world.cpp, core/src/cubos/core/ui/ecs.cpp, core/tests/CMakeLists.txt, core/tests/data/context.cpp, core/tests/ecs/blueprint.cpp, core/tests/ecs/commands.cpp, core/tests/ecs/query.cpp, core/tests/ecs/registry.cpp, core/tests/ecs/utils.hpp, core/tests/ecs/world.cpp, core/tests/utils.hpp, engine/samples/scene/main.cpp, engine/src/cubos/engine/tools/entity_inspector/plugin.cpp, tools/cubinhos/src/generate.cpp
=> Add tests for covering the ECS world

core/include/cubos/core/io/window.hpp, core/samples/debug_renderer.cpp, core/samples/render_device.cpp, core/samples/render_device_compute.cpp, core/samples/ui.cpp, core/src/cubos/core/io/glfw_window.cpp, core/src/cubos/core/io/glfw_window.hpp, core/src/cubos/core/ui/imgui.cpp, engine/include/cubos/engine/input/input.hpp, engine/samples/input/main.cpp, engine/src/cubos/engine/input/action.cpp, engine/src/cubos/engine/input/input.cpp, engine/src/cubos/engine/input/plugin.cpp, engine/src/cubos/engine/renderer/plugin.cpp
No more need to keep state about the pressed keys in Input plugin
=> Move Input plugin's pressed to Window plugin's keyPressed

core/src/cubos/core/ecs/system.cpp, core/tests/CMakeLists.txt, core/tests/ecs/system.cpp
=> Add tests for covering system argument and queries

engine/samples/CMakeLists.txt, engine/samples/empty/main.cpp
=> Remove `engine-sample.empty`

core/CMakeLists.txt, core/src/cubos/core/al/audio_device.cpp, core/src/cubos/core/al/oal_audio_device.cpp, core/src/cubos/core/gl/ogl_render_device.cpp, core/src/cubos/core/io/glfw_window.cpp, core/src/cubos/core/io/glfw_window.hpp, core/src/cubos/core/io/window.cpp, engine/CMakeLists.txt, engine/samples/voxels/main.cpp
Removes src/ from include path
=> Remove src/ from include path

core/include/cubos/core/reflection/traits/fields.hpp, core/samples/reflection/traits/fields/main.cpp, core/samples/reflection/traits/fields/page.md, core/src/cubos/core/reflection/traits/fields.cpp, core/tests/reflection/traits/fields.cpp
Change `FieldsTrait` to use views, like the other structural traits.
=> Use views on `FieldsTrait`

core/include/cubos/core/geom/capsule.hpp, engine/samples/collisions/main.cpp, engine/src/cubos/engine/collisions/broad_phase.cpp
Adds system to setup capsule shaped colliders.
Blocked by #666
=> Generate AABBs for Capsule

core/include/cubos/core/reflection/traits/constructible.hpp, core/samples/reflection/traits/constructible/main.cpp, core/samples/reflection/traits/constructible/page.md, core/src/cubos/core/reflection/traits/constructible.cpp, core/tests/reflection/traits/constructible.cpp, core/tests/reflection/traits/constructible.hpp
=> refactor(reflection): Constructible has*

core/CMakeLists.txt, core/include/cubos/core/memory/any_vector.hpp, core/src/cubos/core/memory/any_vector.cpp, core/tests/CMakeLists.txt, core/tests/memory/any_vector.cpp, core/tests/utils.hpp
=> feat(memory): add AnyVector

core/CMakeLists.txt, core/include/cubos/core/memory/any_value.hpp, core/include/cubos/core/memory/any_vector.hpp, core/src/cubos/core/memory/any_value.cpp, core/tests/CMakeLists.txt, core/tests/memory/any_value.cpp
=> Add `AnyValue`

engine/include/cubos/engine/voxels/palette.hpp, engine/src/cubos/engine/voxels/palette.cpp
=> feat(engine): add push method to VoxelPalette

engine/CMakeLists.txt, engine/include/cubos/engine/tools/debug_camera/plugin.hpp, engine/src/cubos/engine/tools/debug_camera/plugin.cpp, tools/tesseratos/src/main.cpp
=> Toggleable debug camera

engine/samples/voxels/main.cpp
=> Prevent continuous car spawning in `engine-sample.voxels`

engine/samples/input/main.cpp, engine/samples/input/page.md
Added documentation on how to load the input bindings.
=> Add documentation for loading input bindings 

.clang-tidy, core/include/cubos/core/memory/function.hpp, core/include/cubos/core/memory/move.hpp, core/tests/CMakeLists.txt, core/tests/memory/function.cpp
Adds our own `std::forward` to `move.hpp`.
Adds `Function`, which acts just like `std::function`.
=> Implement our own `std::function`

.github/workflows/clang-tidy-lint.yml
Turns out we just had to switch the compiler in the CI action to clang instead of g++ :)
=> fix(ci): revert to clang-tidy 14

.github/workflows/copy-labels.yml
Automatically copy issue labels to linked PRs
=> Automatically copy issue labels to linked PRs

.github/workflows/conventional-commits.yml
Checks if all commits from a PR follow the Conventional Commit format.
=> Add conventional commits action

core/include/cubos/core/reflection/type.hpp, core/src/cubos/core/reflection/type.cpp, core/tests/reflection/type.cpp
- add equality operator for `reflection::Type` that compares by address
- add simple tests for it
=> Implement equality operator for `reflection::Type`

engine/samples/imgui/main.cpp, engine/src/cubos/engine/imgui/data_inspector.cpp
- handle `NullableTrait` in the data inspector
- add more data examples to imgui sample
=> Handle `NullableTrait` in the data inspector

.gitmodules, engine/CMakeLists.txt, engine/src/cubos/engine/imgui/imgui.cpp, tools/tesseratos/CMakeLists.txt, tools/tesseratos/include/tesseratos/metrics_panel/plugin.hpp, tools/tesseratos/src/tesseratos/metrics_panel/plugin.cpp, tools/tesseratos/src/tesseratos/plugin.cpp
=> Metrics Panel

.github/workflows/build-engine-windows.yml
Updated both the glad and the json dependencies to their latest versions, should have fixed the problem.
=> Fix cmake 3.5 version warnings

core/include/cubos/core/ecs/query/data.hpp, core/include/cubos/core/ecs/query/filter.hpp, core/include/cubos/core/ecs/system/query.hpp, core/include/cubos/core/ecs/system/system.hpp, core/include/cubos/core/ecs/types.hpp, core/src/cubos/core/ecs/query/filter.cpp, core/src/cubos/core/ecs/types.cpp, core/src/cubos/core/ecs/world.cpp, core/tests/ecs/query/filter.cpp, engine/include/cubos/engine/scene/bridge.hpp, engine/samples/scene/assets/main.cubos, engine/samples/scene/assets/sub.cubos, engine/samples/scene/components.hpp, engine/samples/scene/main.cpp, engine/samples/scene/page.md, engine/src/cubos/engine/scene/bridge.cpp, engine/src/cubos/engine/scene/plugin.cpp
Add relations to scenes, with a similar syntax to components.
Turns out I forgot to add `::pin` to the user facing Query type, so I added it here. Also found some bugs when pinning symmetric relations with the sample.
Added a new test to cover the bug and fixed it.
=> Add relations to scenes

tools/tesseratos/src/tesseratos/scene_editor/plugin.cpp
=> feat(tesseratos): improve scene editor ui

.github/pull_request_template.md, CHANGELOG.md
=> docs: create CHANGELOG.md

.github/workflows/copy-labels.yml, .github/workflows/create-coverage-report.yml, CHANGELOG.md, CMakeLists.txt
=> Track engine test coverage

tools/tesseratos/src/tesseratos/debug_camera/plugin.cpp
=> feat(tesseratos): add FreeCameraController component and plugin to Debug Camera

core/CMakeLists.txt, core/include/cubos/core/ecs/blueprint.hpp, core/include/cubos/core/ecs/command_buffer.hpp, core/include/cubos/core/ecs/name.hpp, core/include/cubos/core/ecs/system/arguments/commands.hpp, core/include/cubos/core/ecs/world.hpp, core/src/ecs/blueprint.cpp, core/src/ecs/command_buffer.cpp, core/src/ecs/name.cpp, core/src/ecs/system/arguments/commands.cpp, core/src/ecs/world.cpp, core/tests/ecs/blueprint.cpp, tools/tesseratos/src/tesseratos/world_inspector/plugin.cpp
Add Name component so it can be added to entities in world inspector.
=> 266 add name component

core/src/ecs/blueprint.cpp, core/tests/ecs/blueprint.cpp, engine/src/scene/bridge.cpp
=> fix(scene): also handle null entities in scenes

tools/tesseratos/src/tesseratos/entity_inspector/plugin.cpp
=> Show entity generation in entity inspector

engine/src/splitscreen/plugin.cpp
=> fix(rendering): set correct viewport size on splitscreen

core/include/cubos/core/ecs/cubos.hpp, core/include/cubos/core/ecs/system/dispatcher.hpp, core/src/ecs/cubos.cpp, core/src/ecs/system/dispatcher.cpp, core/tests/ecs/dispatcher.cpp
=> Add repeat while to dispatcher

engine/src/collisions/broad_phase/plugin.cpp
=> fix(collisions): handle destroyed entities on sweep and prune correctly

core/include/cubos/core/ecs/blueprint.hpp, core/include/cubos/core/ecs/cubos.hpp, core/include/cubos/core/ecs/system/arguments/query.hpp, core/include/cubos/core/ecs/system/dispatcher.hpp, core/include/cubos/core/ecs/table/dense/registry.hpp, core/include/cubos/core/ecs/table/sparse_relation/registry.hpp, core/include/cubos/core/ecs/types.hpp, core/include/cubos/core/io/window.hpp, core/include/cubos/core/memory/any_vector.hpp, core/include/cubos/core/reflection/reflect.hpp, core/include/cubos/core/reflection/traits/enum.hpp, core/include/cubos/core/reflection/traits/nullable.hpp, core/samples/reflection/traits/enum/page.md, docs/pages/2_features/quadrados.md, engine/include/cubos/engine/gizmos/gizmos.hpp, engine/include/cubos/engine/imgui/data_inspector.hpp, engine/include/cubos/engine/screen_picker/screen_picker.hpp, engine/samples/events/main.cpp, flake.nix
=> Documentation cant be built due to lack of support for concepts on mcss

core/src/geom/intersections.cpp
Discord reviews are the new meta.
Simplified intersects function and overlap checking and calculation.
Added correct calculation of overlap for cases of containment.
=> Small refactor to box-box intersection

CHANGELOG.md, engine/src/gizmos/plugin.cpp, engine/src/physics/plugin.cpp, engine/src/splitscreen/plugin.cpp
=> fix(engine): add missing plugin dependencies

CHANGELOG.md, core/CMakeLists.txt, core/include/cubos/core/ecs/entity/archetype_graph.hpp, core/include/cubos/core/ecs/query/data.hpp, core/include/cubos/core/ecs/query/fetcher.hpp, core/include/cubos/core/ecs/query/filter.hpp, core/include/cubos/core/ecs/query/node/archetype.hpp, core/include/cubos/core/ecs/query/node/node.hpp, core/include/cubos/core/ecs/query/node/related.hpp, core/include/cubos/core/ecs/table/sparse_relation/id.hpp, core/include/cubos/core/ecs/table/sparse_relation/table.hpp, core/include/cubos/core/ecs/types.hpp, core/include/cubos/core/ecs/world.hpp, core/src/ecs/entity/archetype_graph.cpp, core/src/ecs/query/filter.cpp, core/src/ecs/query/node/archetype.cpp, core/src/ecs/query/node/node.cpp, core/src/ecs/query/node/related.cpp, core/src/ecs/table/sparse_relation/table.cpp, core/src/ecs/world.cpp, core/tests/ecs/cubos.cpp, core/tests/ecs/query/filter.cpp, core/tests/ecs/stress.cpp, core/tests/ecs/table/sparse_relation/table.cpp, core/tests/ecs/utils/action.cpp, core/tests/ecs/utils/action.hpp, core/tests/ecs/world.cpp, engine/src/collisions/broad_phase/plugin.cpp, flake.nix
Also unlocks the possiblity of having more than 2 query targets and relations.
=> Fix random ECS stress test failure and multiple other bugs

CHANGELOG.md, docs/pages/2_features/ecs.md, docs/pages/2_features/main.md, docs/pages/2_features/plugins.md, docs/pages/2_features/queries.md, engine/include/cubos/engine/collisions/colliding_with.hpp
=> Add query feature guide

CHANGELOG.md, core/include/cubos/core/ecs/entity/pool.hpp, core/include/cubos/core/ecs/table/sparse_relation/registry.hpp, core/include/cubos/core/ecs/world.hpp, core/src/ecs/entity/pool.cpp, core/src/ecs/world.cpp, tools/tesseratos/CMakeLists.txt, tools/tesseratos/include/tesseratos/ecs_statistics/plugin.hpp, tools/tesseratos/src/tesseratos/ecs_statistics/plugin.cpp, tools/tesseratos/src/tesseratos/plugin.cpp
=> Add ECS debug tool to the editor

CHANGELOG.md, core/include/cubos/core/ecs/query/opt.hpp, core/tests/ecs/cubos.cpp, core/tests/ecs/dispatcher.cpp, tools/tesseratos/src/tesseratos/ecs_statistics/plugin.cpp
=> System condition is never evaluated

CHANGELOG.md, engine/src/utils/free_camera/plugin.cpp
=> fix(engine): fix free camera controller angle not being bounded

engine/src/physics/plugin.cpp, engine/src/transform/plugin.cpp, engine/tests/transform.cpp
=> Change existing code to use observers where applicable

.github/CODEOWNERS, CHANGELOG.md, core/include/cubos/core/ecs/cubos.hpp, core/src/ecs/cubos.cpp, engine/include/cubos/engine/utils/free_camera/controller.hpp, engine/samples/physics/main.cpp, engine/src/fixed_step/plugin.cpp, engine/src/gizmos/plugin.cpp, engine/src/utils/free_camera/controller.cpp, engine/src/utils/free_camera/plugin.cpp, tools/tesseratos/src/tesseratos/debug_camera/plugin.cpp, tools/tesseratos/src/tesseratos/metrics_panel/plugin.cpp, tools/tesseratos/src/tesseratos/play_pause/plugin.cpp
Allows accessing the unscaled delta time, and changes the debug camera to use it.
=> Add getter for the unscaled delta time

CHANGELOG.md, tools/tesseratos/include/tesseratos/transform_gizmo/plugin.hpp, tools/tesseratos/src/tesseratos/transform_gizmo/plugin.cpp
=> feat(gizmos): make transform gizmo have constant size

CHANGELOG.md, engine/CMakeLists.txt, engine/include/cubos/engine/render/depth/depth.hpp, engine/include/cubos/engine/render/depth/plugin.hpp, engine/include/cubos/engine/render/g_buffer/plugin.hpp, engine/include/cubos/engine/render/target/plugin.hpp, engine/src/render/depth/depth.cpp, engine/src/render/depth/plugin.cpp
Adds the renderDepthPlugin, which adds and manages the RenderDepth component.
=> Add RenderDepth plugin

CHANGELOG.md, engine/CMakeLists.txt, engine/include/cubos/engine/render/hdr/hdr.hpp, engine/include/cubos/engine/render/hdr/plugin.hpp, engine/src/render/hdr/hdr.cpp, engine/src/render/hdr/plugin.cpp
=> Add HDR plugin

CHANGELOG.md, core/include/cubos/core/reflection/type.hpp, core/src/reflection/type.cpp, core/tests/reflection/type.cpp, tools/tesseratos/samples/main/assets/scenes/main.cubos, tools/tesseratos/samples/main/assets/tesseratos.bind, tools/tesseratos/src/tesseratos/entity_inspector/plugin.cpp, tools/tesseratos/src/tesseratos/world_inspector/plugin.cpp
=> Allow filtering by components and name on world inspector

CHANGELOG.md, core/src/gl/ogl_render_device.cpp, core/src/gl/ogl_render_device.hpp
=> fix(rendering): destroy objects only if render device is alive

CHANGELOG.md, tools/tesseratos/src/tesseratos/entity_inspector/plugin.cpp
Closes #1022.
Shows relations on the entity inspector, and allows adding and removing them.
=> Show relations on the entity inspector

CHANGELOG.md, engine/CMakeLists.txt, engine/include/cubos/engine/render/voxels/grid.hpp, engine/include/cubos/engine/render/voxels/load.hpp, engine/include/cubos/engine/render/voxels/palette.hpp, engine/include/cubos/engine/render/voxels/plugin.hpp, engine/src/render/voxels/grid.cpp, engine/src/render/voxels/load.cpp, engine/src/render/voxels/palette.cpp, engine/src/render/voxels/plugin.cpp
Adds the render voxels plugin, which defines the interface (components) for different voxel rendering plugins.
=> feat(rendering): add Render Voxels plugin

CHANGELOG.md, engine/CMakeLists.txt, engine/assets/render/deferred_shading.fs, engine/assets/render/deferred_shading.fs.meta, engine/include/cubos/engine/render/deferred_shading/deferred_shading.hpp, engine/include/cubos/engine/render/deferred_shading/plugin.hpp, engine/samples/render/assets/main.cubos, engine/samples/render/main.cpp, engine/src/render/deferred_shading/deferred_shading.cpp, engine/src/render/deferred_shading/plugin.cpp
=> feat(rendering): add Deferred Shading plugin

core/include/cubos/core/ecs/query/data.hpp, core/include/cubos/core/ecs/query/fetcher.hpp, core/include/cubos/core/ecs/query/filter.hpp, core/include/cubos/core/ecs/query/node/node.hpp, core/include/cubos/core/memory/guards.hpp, core/src/ecs/command_buffer.cpp, core/src/ecs/query/filter.cpp, core/src/ecs/query/node/archetype.cpp, core/src/ecs/query/node/related.cpp, core/tests/ecs/query/data.cpp, engine/include/cubos/engine/input/input.hpp, engine/src/collisions/broad_phase/plugin.cpp, engine/src/input/input.cpp, engine/src/scene/bridge.cpp, tools/tesseratos/src/tesseratos/collider_gizmos/plugin.cpp
=> Coffee jam

engine/include/cubos/engine/assets/assets.hpp, engine/src/assets/assets.cpp, tools/tesseratos/src/tesseratos/asset_explorer/popup.cpp, tools/tesseratos/src/tesseratos/scene_editor/plugin.cpp
=> 552 implement adding sub scenes in the scene editor

CHANGELOG.md, CMakeLists.txt
=> Bump cmake project ver

CHANGELOG.md, core/CMakeLists.txt, core/include/cubos/core/metrics.hpp, core/samples/CMakeLists.txt, core/samples/metrics/main.cpp, core/samples/metrics/page.md, core/src/metrics.cpp, core/tests/CMakeLists.txt, core/tests/metrics/metrics.cpp
**Check the sample for usage**
TLDR: The goal is to have a simple but extendible core class to register, search and debug metrics, with a compiler option to enable it
=> Implement metrics

CHANGELOG.md, engine/CMakeLists.txt, engine/include/cubos/engine/render/shadows/caster.hpp, engine/include/cubos/engine/render/shadows/directional_caster.hpp, engine/include/cubos/engine/render/shadows/plugin.hpp, engine/include/cubos/engine/render/shadows/point_caster.hpp, engine/include/cubos/engine/render/shadows/spot_caster.hpp, engine/src/render/shadows/caster.cpp, engine/src/render/shadows/directional_caster.cpp, engine/src/render/shadows/plugin.cpp, engine/src/render/shadows/point_caster.cpp, engine/src/render/shadows/spot_caster.cpp
Adds the base interface plugin for shadows, which registers shadow caster components.
=> Add shadows plugin

flake.lock, flake.nix
NixOS 23.11 -> 24.05
Stop using custom version doxygen, nixpkgs has caught up to us
Configure LD_LIBRARY_PATH
=> Bump flake to NixOS 24.05

CHANGELOG.md, tools/tesseratos/CMakeLists.txt, tools/tesseratos/src/tesseratos/console/plugin.cpp, tools/tesseratos/src/tesseratos/console/plugin.hpp, tools/tesseratos/src/tesseratos/main.cpp
Create a console plugin to be able to visualize the logs in tesseratos.
=> Add Console plugin

CHANGELOG.md, engine/include/cubos/engine/assets/asset.hpp, engine/include/cubos/engine/assets/assets.hpp, engine/include/cubos/engine/assets/meta.hpp, engine/samples/games/cubosurfers/main.cpp, engine/src/assets/asset.cpp, engine/src/assets/assets.cpp, engine/src/assets/meta.cpp, engine/src/render/g_buffer_rasterizer/plugin.cpp, engine/src/render/mesh/plugin.cpp, engine/src/scene/bridge.cpp, tools/tesseratos/src/tesseratos/importer/plugin.cpp, tools/tesseratos/src/tesseratos/scene_editor/plugin.cpp
Changed some logic to the assets system to identify assets by their path.
=> feat(assets): Allowed identifying assets in code from their path

CHANGELOG.md, engine/CMakeLists.txt, engine/include/cubos/engine/audio/audio.hpp, engine/include/cubos/engine/audio/bridge.hpp, engine/src/audio/audio.cpp, engine/src/audio/bridge.cpp
This is on PR of many in #231, adds an Audio Asset.
Closes #230.
=> Add Audio Asset

CHANGELOG.md, engine/CMakeLists.txt, engine/assets/render/g_buffer_rasterizer.vs, engine/include/cubos/engine/collisions/collider.hpp, engine/include/cubos/engine/collisions/raycast.hpp, engine/include/cubos/engine/fixed_step/fixed_accumulated_time.hpp, engine/include/cubos/engine/fixed_step/plugin.hpp, engine/src/audio/source.cpp, engine/src/collisions/broad_phase/plugin.cpp, engine/src/collisions/interface/collider.cpp, engine/src/collisions/interface/raycast.cpp, engine/src/fixed_step/fixed_accumulated_time.cpp, engine/src/fixed_step/plugin.cpp, engine/src/input/input.cpp, engine/src/render/ssao/plugin.cpp, engine/src/tools/transform_gizmo/plugin.cpp, engine/src/utils/free_camera/plugin.cpp, flake.nix
Branch with all of the demo hotfixes.
=> Demo hotfixes

CHANGELOG.md, core/CMakeLists.txt, core/include/cubos/core/geom/frustum.hpp, core/include/cubos/core/geom/intersections.hpp, core/include/cubos/core/geom/utils.hpp, core/src/geom/frustum.cpp, core/src/geom/intersections.cpp, core/src/geom/utils.cpp
Added Frustum made of 6 planes to the core geometry, and two intersection functions for box and capsule.
=> Add frustum and intersection functions

engine/src/render/deferred_shading/plugin.cpp
Verify if a caster has a shadowmap at the cameraEntity entrance.
=> fix(render): crash when adding shadow casters

CHANGELOG.md, engine/assets/render/deferred_shading.fs, engine/src/render/deferred_shading/plugin.cpp
TL;DR padding was needed, for some reason it only affects web builds
=> fix(rendering): deferred shading plugin on web

CHANGELOG.md, core/include/cubos/core/ecs/system/arguments/query.hpp, core/tests/ecs/query.cpp
Added a method to Query to count the number of matches
=> feat(ecs): add a method to Query to count the number of matches

CHANGELOG.md, tools/tesseratos/CMakeLists.txt, tools/tesseratos/src/tesseratos/asset_explorer/plugin.cpp, tools/tesseratos/src/tesseratos/asset_explorer/plugin.hpp, tools/tesseratos/src/tesseratos/debugger/plugin.cpp, tools/tesseratos/src/tesseratos/debugger/plugin.hpp, tools/tesseratos/src/tesseratos/importer/plugin.cpp, tools/tesseratos/src/tesseratos/importer/plugin.hpp, tools/tesseratos/src/tesseratos/main.cpp, tools/tesseratos/src/tesseratos/menu_bar/plugin.cpp, tools/tesseratos/src/tesseratos/menu_bar/plugin.hpp, tools/tesseratos/src/tesseratos/project/plugin.cpp, tools/tesseratos/src/tesseratos/project/plugin.hpp, tools/tesseratos/src/tesseratos/scene_editor/plugin.cpp, tools/tesseratos/src/tesseratos/scene_editor/plugin.hpp, tools/tesseratos/src/tesseratos/voxel_palette_editor/plugin.cpp, tools/tesseratos/src/tesseratos/voxel_palette_editor/plugin.hpp
Adds a menu bar plugin to Tesseratos. This plugin acts somewhat like the Toolbox plugin, except it interacts directly with the tools themselves.
=> 1234 add a menu bar to tesseratos

engine/include/cubos/engine/render/camera/perspective.hpp, engine/src/render/camera/plugin.cpp, engine/src/render/g_buffer_rasterizer/plugin.cpp
=> Fix frustum culling

CHANGELOG.md, bindings/CMakeLists.txt, bindings/lua/CMakeLists.txt, bindings/lua/include/cubos/bindings/lua/plugin.hpp, bindings/lua/samples/CMakeLists.txt, bindings/lua/samples/hello_world/main.cpp, bindings/lua/samples/hello_world/scripts/hello.lua, bindings/lua/src/plugin.cpp
Add lua bindings plugin to be able to execute lua code.
=> 1497 add lua bindings plugin
