core/CMakeLists.txt
core/include/cubos/data/archive.hpp
core/include/cubos/data/file.hpp
core/include/cubos/data/file_stream.hpp
core/include/cubos/data/file_system.hpp
core/include/cubos/data/std_archive.hpp
core/include/cubos/memory/buffer_stream.hpp
core/include/cubos/memory/std_stream.hpp
core/include/cubos/memory/stream.hpp
core/src/cubos/data/file.cpp
core/src/cubos/data/file_system.cpp
core/src/cubos/data/std_archive.cpp
core/src/cubos/memory/buffer_stream.cpp
core/src/cubos/memory/std_stream.cpp
core/src/cubos/memory/stream.cpp
core/tests/CMakeLists.txt
core/tests/test_std_archive.cpp

Closes #16.
- adds the `File` class, which represents a `File` in the virtual file system.
- adds the generic `Archive` class, which acts as a mount point from the real file system to the virtual one.
- implements the `STDArchive` class, which is an archive used to mount OS directories or files.
- adds the `FileSystem` class, used as a utility to manage the entire virtual file system.
- added a test for `STDArchive`.
Compressed archives will be left for future implementation since they're not a priority right now. Check #81

FileSystem and STDArchive

---

core/CMakeLists.txt
core/include/cubos/gl/render_device.hpp
core/src/cubos/gl/ogl_render_device.cpp
core/src/cubos/gl/ogl_render_device.hpp
core/src/cubos/gl/render_device.cpp

- Wrong GLenum equivalents fixed
- Use std::variant instead of union in framebuffer targets
- Use set*Target methods in framebuffer targets instead of setting values directly.

Various Fixes in RenderDevice

---

core/CMakeLists.txt
core/include/cubos/core/data/debug_serializer.hpp
core/include/cubos/core/log.hpp
core/include/cubos/core/memory/buffer_stream.hpp
core/include/cubos/core/memory/stream.hpp
core/samples/CMakeLists.txt
core/samples/logging.cpp
core/src/cubos/core/data/debug_serializer.cpp
core/src/cubos/core/memory/buffer_stream.cpp
core/src/cubos/core/memory/stream.cpp

Closes #173
Closes #140
- Add new DebugSerializer 
- Integrated this serializer with fmt so that it is used automatically when logging.
- Added a new logging sample to exemplify this usage.
- Made spdlog use the external fmt we were already using.

Add debug serializer with fmt integration

---

core/src/cubos/core/ecs/dispatcher.cpp
engine/CMakeLists.txt
engine/include/cubos/engine/cubos.hpp
engine/include/cubos/engine/plugins/window.hpp
engine/samples/assets/scenes/main.cubos
engine/samples/scene.cpp
engine/src/cubos/engine/cubos.cpp
engine/src/cubos/engine/plugins/window.cpp
tools/src/convert.cpp
tools/src/embed.cpp
tools/src/generate.cpp

This implement our first core plugin, `windowPlugin`, which users should add if they want to show output to a window. With this, window generation, polling and swapping buffers is handled internally by the engine.
A few bugs had to be fixed too:
- The dispatcher had a bug when a given element was erased from the stages; this may invalidate the `refIt` iterator, causing a crash.
- Some `Options` objects were not initialized on `cubinhos`, causing crashes.
(Rebasing this was becoming ugly, so I had to make a temporary `cubos_class_window_copy` branch. Please only delete this after this is merged, just in case TM)

Implement window plugin

---

engine/src/cubos/engine/plugins/imgui.cpp
engine/src/cubos/engine/plugins/window.cpp

Closes #285.
After merging #297, the ImGui samples have stopped working. This happened because #202 had not been finished yet and we couldn't communicate the events from the window plugin to the ImGui plugin.

Fix ImGui samples

---

.github/workflows/build-engine-macos.yml

macOS image [was updated](https://github.com/actions/runner-images/releases/tag/macOS-12%2F20230117.3) and the default version is now 15, so we install v14 with brew before.

Fix macOS CI compilation

---

core/include/cubos/core/ecs/dispatcher.hpp
core/src/cubos/core/ecs/dispatcher.cpp
engine/include/cubos/engine/cubos.hpp
engine/samples/systems/main.cpp
engine/src/cubos/engine/cubos.cpp

Closes #292 
Implement proper tag inheritance, which was left to do after the initial dispatcher rework.
Other than that, I found some bugs on the dispatcher along the way that were fixed. I also introduced a warning when users use tags from opposite system types:
```cpp
cubos.tag("A"); // Main tag
cubos.startupSystem(a).tagged("A"); // Startup system, tag mismatch
```

Implement tag inheritance

---

core/include/cubos/core/ecs/dispatcher.hpp
core/samples/ecs.cpp
core/src/cubos/core/ecs/dispatcher.cpp
engine/include/cubos/engine/plugins/env_settings.hpp
engine/include/cubos/engine/plugins/file_settings.hpp
engine/include/cubos/engine/plugins/imgui.hpp
engine/include/cubos/engine/plugins/renderer.hpp
engine/include/cubos/engine/plugins/tools/entity_selector.hpp
engine/include/cubos/engine/plugins/tools/settings_inspector.hpp
engine/include/cubos/engine/plugins/transform.hpp
engine/include/cubos/engine/plugins/window.hpp
engine/samples/scene/main.cpp
engine/src/cubos/engine/cubos.cpp
engine/src/cubos/engine/plugins/env_settings.cpp
engine/src/cubos/engine/plugins/file_settings.cpp
engine/src/cubos/engine/plugins/imgui.cpp
engine/src/cubos/engine/plugins/renderer.cpp
engine/src/cubos/engine/plugins/tools/settings_inspector.cpp
engine/src/cubos/engine/plugins/transform.cpp
engine/src/cubos/engine/plugins/window.cpp

Closes #303 and #326.
Originally this PR only aimed to improve the plugin docs and change the tag names to fit #303.
I then found out that a system couldn't be tagged twice, which made some code more difficult to read, and decided to fix it.

Allow multiple system tags and cleanup existing plugin code

---

engine/CMakeLists.txt
engine/include/cubos/engine/assets/binary_bridge.hpp
engine/include/cubos/engine/voxels/grid_bridge.hpp
engine/include/cubos/engine/voxels/palette_bridge.hpp
engine/include/cubos/engine/voxels/plugin.hpp
engine/src/cubos/engine/assets/binary_bridge.cpp
engine/src/cubos/engine/voxels/plugin.cpp

Add the `voxelsPlugin`, which adds two assets bridges: `GridBridge` and `PaletteBridge`.
Since both assets are just binary (de)serialized, abstractions `BinaryBridge` and `BinaryBridgeImpl` were created to reduce code duplication.

Add voxels plugin

---

engine/include/cubos/engine/assets/assets.hpp
engine/include/cubos/engine/assets/bridge.hpp
engine/include/cubos/engine/assets/bridges/binary.hpp
engine/include/cubos/engine/assets/bridges/file.hpp
engine/include/cubos/engine/assets/bridges/json.hpp
engine/include/cubos/engine/scene/bridge.hpp
engine/samples/assets/bridge/main.cpp
engine/src/cubos/engine/assets/assets.cpp

closes #478 
Added a function that allows getting the type of an asset, even before it is loaded.

Allow getting the type of an asset

---

core/include/cubos/core/ecs/dispatcher.hpp
engine/include/cubos/engine/cubos.hpp
engine/samples/cars/main.cpp
engine/samples/collisions/main.cpp
engine/samples/events/main.cpp
engine/samples/input/main.cpp
engine/samples/renderer/main.cpp
engine/samples/scene/main.cpp
engine/samples/systems/main.cpp
engine/src/cubos/engine/assets/plugin.cpp
engine/src/cubos/engine/collisions/plugin.cpp
engine/src/cubos/engine/cubos.cpp
engine/src/cubos/engine/imgui/plugin.cpp
engine/src/cubos/engine/input/plugin.cpp
engine/src/cubos/engine/renderer/plugin.cpp
engine/src/cubos/engine/window/plugin.cpp

Removed all code related to ordering systems by systems, and renamed `afterTag()` and `beforeTag()` to `after()` and `before()`, respectively.

Remove afterSystem and beforeSystem

---

core/CMakeLists.txt
core/include/cubos/core/al/module.dox
core/include/cubos/core/data/fs/module.dox
core/include/cubos/core/data/module.dox
core/include/cubos/core/ecs/module.dox
core/include/cubos/core/geom/module.dox
core/include/cubos/core/gl/module.dox
core/include/cubos/core/io/module.dox
core/include/cubos/core/memory/module.dox
core/include/cubos/core/module.dox
core/include/cubos/core/reflection/module.dox
core/include/cubos/core/reflection/reflect.hpp
core/include/cubos/core/reflection/type.hpp
core/include/cubos/core/ui/module.dox
core/samples/CMakeLists.txt
core/samples/reflection/basic/main.cpp
core/samples/reflection/basic/page.md
core/src/cubos/core/reflection/type.cpp
core/tests/CMakeLists.txt
core/tests/reflection/reflect.cpp
core/tests/reflection/type.cpp
docs/pages/3_examples/1_core/main.md
engine/include/cubos/engine/module.dox

Add:
- `reflect.hpp` file which defines reflection macros and the `reflect` function, used to fetch reflection data.
- `Type` class, which stores the type's name and its traits.
- `core-sample.reflection` which shows how to use types and traits.

Add `Type` class and reflection macros and functions

---

core/CMakeLists.txt
core/include/cubos/core/memory/move.hpp
core/include/cubos/core/reflection/module.dox
core/include/cubos/core/reflection/traits/constructible.hpp
core/include/cubos/core/reflection/traits/constructible_utils.hpp
core/include/cubos/core/reflection/traits/module.dox
core/samples/CMakeLists.txt
core/samples/reflection/basic/page.md
core/samples/reflection/page.md
core/samples/reflection/traits/constructible/main.cpp
core/samples/reflection/traits/constructible/page.md
core/src/cubos/core/reflection/traits/constructible.cpp
core/tests/CMakeLists.txt
core/tests/reflection/traits/constructible.cpp
docs/pages/3_examples/1_core/main.md

Adds the `ConstructibleTrait`, which holds the default, copy and move constructors of a type, and its size, alignment and destructor.
This is useful for creating and managing new instances of type-erased data.

Add `ConstructibleTrait`

---

core/CMakeLists.txt
core/include/cubos/core/reflection/external/module.dox
core/include/cubos/core/reflection/external/primitives.hpp
core/src/cubos/core/reflection/external/primitives.cpp
core/tests/CMakeLists.txt
core/tests/reflection/external/primitives.cpp
core/tests/reflection/traits/constructible.hpp

Implement reflection for boolean, char, integer and floating point types.

Define reflection for primitive types

---

docs/pages/3_examples/2_engine/main.md
engine/samples/events/main.cpp
engine/samples/events/page.md

Cleanup and document `engine-sample.events`

---

core/include/cubos/core/reflection/traits/fields.hpp
core/samples/reflection/traits/fields/main.cpp
core/src/cubos/core/reflection/traits/fields.cpp
core/tests/reflection/external/glm.cpp

Views getters and setters should also receive a field name string

---

engine/src/cubos/engine/input/axis.cpp

Stopped using `std::clamp` instead of including `<algorithm>`.

Do not use `std::clamp` on axis.cpp

---

flake.nix

Required for the `clang-format` hook to work.

Add `clang-tools` to flake.nix

---

docs/pages/4_contribution/main.md

Updated the guidelines to reflect the discussed new scopes.

Update commit scope guidelines

---

core/src/cubos/core/gl/ogl_render_device.cpp

Read the #633 for more information.

Correctly check if anisotropy extension is available in `OGLRenderDevice`

---

engine/src/cubos/engine/tools/scene_editor/plugin.cpp

Closes #630
Previously compilation was failing due to `std::vector<std::pair<std::string, SceneInfo>>` not supporting forward declared `SceneInfo` on some compilers.
By storing a pointer to `SceneInfo` instead, we make it okay to do so.

Store SceneInfo through a pointer instead of by value

---

.clang-tidy
CMakeLists.txt
engine/src/cubos/engine/tools/scene_editor/plugin.cpp

Blocked by #631.
Add include checks.
Disable `clang-tidy` by default.

Add include checks to clang tidy and disable it by default

---

core/CMakeLists.txt
core/include/cubos/core/ecs/blueprint.hpp
core/include/cubos/core/ecs/dispatcher.hpp
core/include/cubos/core/ecs/system/accessors.hpp
core/include/cubos/core/ecs/system/commands.hpp
core/include/cubos/core/ecs/system/dispatcher.hpp
core/include/cubos/core/ecs/system/event/pipe.hpp
core/include/cubos/core/ecs/system/event/reader.hpp
core/include/cubos/core/ecs/system/event/writer.hpp
core/include/cubos/core/ecs/system/module.dox
core/include/cubos/core/ecs/system/query.hpp
core/include/cubos/core/ecs/system/system.hpp
core/samples/ecs/events/main.cpp
core/samples/ecs/general/main.cpp
core/src/cubos/core/ecs/system/commands.cpp
core/src/cubos/core/ecs/system/dispatcher.cpp
core/src/cubos/core/ecs/system/system.cpp
core/tests/ecs/commands.cpp
core/tests/ecs/dispatcher.cpp
core/tests/ecs/query.cpp
core/tests/ecs/system.cpp
engine/include/cubos/engine/cubos.hpp
engine/samples/events/main.cpp
engine/src/cubos/engine/collisions/broad_phase.hpp
engine/src/cubos/engine/cubos.cpp
engine/src/cubos/engine/renderer/plugin.cpp
engine/src/cubos/engine/tools/scene_editor/plugin.cpp

Closes #643.
Moves all system related code to the `ecs/system` dir.

Move system stuff to the `ecs/system` directory

---

core/include/cubos/core/ecs/resource/manager.hpp
core/include/cubos/core/ecs/resource/module.dox
core/include/cubos/core/ecs/world.hpp

Closes #646.
Moves the resource manager to the `ecs/resource` directory.

Move resource stuff to the `ecs/resource` directory

---

.clang-format

Removed duplicate key `SortIncludes` mapping.

fix(meta): fixed `.clang-format`

---

core/include/cubos/core/memory/unordered_bimap.hpp
core/tests/CMakeLists.txt
core/tests/memory/unordered_bimap.cpp

Add `UnorderedBimap`

---

core/include/cubos/core/ecs/blueprint.hpp
core/include/cubos/core/ecs/component/manager.hpp
core/include/cubos/core/ecs/component/registry.hpp
core/include/cubos/core/memory/type_map.hpp
core/src/cubos/core/ecs/blueprint.cpp
core/src/cubos/core/ecs/component/manager.cpp
core/src/cubos/core/ecs/component/registry.cpp
core/src/cubos/core/ecs/world.cpp
core/tests/CMakeLists.txt
core/tests/ecs/registry.cpp
core/tests/ecs/system.cpp
core/tests/memory/type_map.cpp

Changes `TypeMap` to use reflection instead of `std::type_index`.
Had to change existing ECS code which depended on this use the reflection type instead of `std::type_index`.
Most of that code will be removed or refactored on a later PR.

feat(memory): use reflection on TypeMap

---

engine/include/cubos/engine/assets/asset.hpp

Fixed crashing when loading assets.

 fix(engine): add assignment of 'reflectedId' in AnyAsset::operator Asset<T>()

---

engine/src/cubos/engine/tools/world_inspector/plugin.cpp

Fixed wrong ID displayed on the World Inspector by using `entity.index` instead of loop index(`n` )

Wrong ID displayed on the World Inspector

---

engine/include/cubos/engine/voxels/palette.hpp
engine/src/cubos/engine/voxels/palette.cpp

Add `VoxelPalette` iterator

---

engine/include/cubos/engine/assets/asset.hpp
engine/src/cubos/engine/assets/asset.cpp

Implemented equality operator for AnyAsset that checks **only for UUID**.

Implement equality operator for `AnyAsset`

---

engine/include/cubos/engine/assets/assets.hpp
engine/include/cubos/engine/renderer/plugin.hpp
engine/src/cubos/engine/renderer/plugin.cpp

Renderer now has a resource `ActiveVoxelPalette` which stores a handle to the current palette asset.

Add `ActiveVoxelPalette` resource to `rendererplugin`

---

core/include/cubos/core/ecs/blueprint.hpp
core/include/cubos/core/ecs/component/manager.hpp
core/include/cubos/core/ecs/component/map_storage.hpp
core/include/cubos/core/ecs/component/null_storage.hpp
core/include/cubos/core/ecs/component/registry.hpp
core/include/cubos/core/ecs/component/storage.hpp
core/include/cubos/core/ecs/component/vec_storage.hpp
core/include/cubos/core/ecs/system/commands.hpp
core/include/cubos/core/memory/type_map.hpp
core/samples/ecs/general/main.cpp
core/src/cubos/core/ecs/blueprint.cpp
core/src/cubos/core/ecs/component/manager.cpp
core/src/cubos/core/ecs/system/commands.cpp
core/tests/ecs/blueprint.cpp
core/tests/ecs/registry.cpp
core/tests/ecs/utils.cpp
core/tests/ecs/utils.hpp
engine/src/cubos/engine/scene/bridge.cpp
engine/src/cubos/engine/tools/scene_editor/plugin.cpp

Changes `Blueprint` to use only reflection and none of the old serialization code.
Changes `Commands` to support the new `Blueprint` interface.
Changes component storages so that type-erased components can be added to them.

Stop using old serialization in `Blueprint`

---

core/include/cubos/core/data/fs/file_system.hpp
core/src/cubos/core/data/fs/file.cpp
core/src/cubos/core/data/fs/file_system.cpp
core/tests/data/fs/file_system.cpp
engine/src/cubos/engine/assets/bridges/file.cpp

Added `FileSystem::copy` and basically it tries to create a `.swp` file and save the contents there. In case it fails, nothing happens to the original asset file. If everything goes right, we copy the contents from `.swp` to the original file

Asset is nuked when save fails

---

core/include/cubos/core/ecs/component/manager.hpp
core/include/cubos/core/ecs/component/map_storage.hpp
core/include/cubos/core/ecs/component/null_storage.hpp
core/include/cubos/core/ecs/component/storage.hpp
core/include/cubos/core/ecs/component/vec_storage.hpp
core/include/cubos/core/ecs/system/query.hpp
core/include/cubos/core/ecs/world.hpp
core/src/cubos/core/ecs/component/manager.cpp
core/src/cubos/core/ecs/world.cpp
core/tests/ecs/blueprint.cpp
core/tests/ecs/commands.cpp
core/tests/ecs/query.cpp
core/tests/ecs/world.cpp

Adds `Components` and `ConstComponents` to world, views which can be used to access the components in an entity directly through the `World`. Moved existing `.add`, `.remove` methods to `Components`. Example usage:
```cpp
world.components(myEntity).add(Position{...});
world.components(myEntity).get<Position>().x = 2;
for (auto [type, value] : world.components(myEntity)
{
// type is a reflection type
// value is a void* to the component
}
```

Allow accessing components in an entity through `World`

---

core/CMakeLists.txt
core/include/cubos/core/data/ser/debug.hpp
core/include/cubos/core/reflection/external/string.hpp
core/src/cubos/core/data/ser/debug.cpp
core/src/cubos/core/data/ser/serializer.cpp
core/src/cubos/core/reflection/external/string.cpp
core/tests/CMakeLists.txt
core/tests/data/ser/debug.cpp
core/tests/reflection/external/string.cpp

Implements reflection for `std::string`, which was still missing.
Adds a new `DebugSerializer` which implements the reflection based `Serializer`.

Add `DebugSerializer` 

---

.github/workflows/build-doxygen-docs.yml
.github/workflows/preview-docs.yml
docs/Doxyfile
docs/conf.py

Closes #563.
Since `cubos-blog` now deploys to the root of the `gh-pages` branch of this repo, this PR changes the path of the docs deploy to the `docs` subdirectory.

feat(ci): deploy docs to subdirs

---

.github/workflows/clang-tidy-lint.yml

All static analysis actions are failing due to this [issue](https://github.com/actions/runner-images/issues/8659).

fix(ci): bump clang-tidy to 17

---

engine/include/cubos/engine/collisions/collision_event.hpp
engine/src/cubos/engine/collisions/broad_phase/candidates.cpp
engine/src/cubos/engine/collisions/plugin.cpp

Emits AABB collision events, an hack just for DevGamm. This should eventually be redesigned once narrow phase is implemented.

Emit Collision Events

---

core/CMakeLists.txt
core/include/cubos/core/data/des/json.hpp
core/include/cubos/core/reflection/traits/array.hpp
core/include/cubos/core/reflection/traits/dictionary.hpp
core/include/cubos/core/reflection/traits/fields.hpp
core/src/cubos/core/data/des/json.cpp
core/src/cubos/core/reflection/traits/array.cpp
core/src/cubos/core/reflection/traits/dictionary.cpp
core/src/cubos/core/reflection/traits/fields.cpp
core/tests/CMakeLists.txt
core/tests/data/des/json.cpp
core/tests/reflection/traits/fields.cpp

Adds `JSONDeserializer`, which implements the new reflection based `Deserializer` by reading data from `nlohmann::json` objects.
Adds `clear` to `DictionaryTrait` and `ArrayTrait`, and `resize` to the latter.
Adds `size` to `FieldsTrait`.

Add `JSONDeserializer`

---

core/include/cubos/core/data/ser/serializer.hpp
core/samples/data/ser/custom/main.cpp
core/src/cubos/core/data/des/deserializer.cpp
core/src/cubos/core/data/ser/debug.cpp
core/src/cubos/core/data/ser/serializer.cpp
core/tests/data/ser/debug.cpp

Use the new `Function` for hooks in the serializer, just like we do on `Deserializer`.

Use `Function` for hooks on `Serializer`

---

engine/CMakeLists.txt
engine/include/cubos/engine/assets/assets.hpp
engine/include/cubos/engine/assets/bridge.hpp
engine/include/cubos/engine/assets/bridges/binary.hpp
engine/include/cubos/engine/assets/bridges/file.hpp
engine/include/cubos/engine/assets/bridges/json.hpp
engine/include/cubos/engine/input/bindings.hpp
engine/include/cubos/engine/scene/bridge.hpp
engine/include/cubos/engine/scene/scene.hpp
engine/samples/assets/bridge/main.cpp
engine/samples/assets/json/main.cpp
engine/samples/assets/saving/main.cpp
engine/src/cubos/engine/assets/assets.cpp
engine/src/cubos/engine/input/bindings.cpp
engine/src/cubos/engine/scene/scene.cpp
tools/tesseratos/src/tesseratos/scene_editor/plugin.cpp
tools/tesseratos/src/tesseratos/voxel_palette_editor/plugin.cpp

~~Blocked by #799~~ and uses commits from #775
- Replace `typeid` by reflection on asset bridges
- Fixed tesseratos plugins where asset types are compared
- Fixed assets samples to use this new system

Replace `typeid` by reflection on asset bridges

---

core/include/cubos/core/ecs/component/manager.hpp
core/include/cubos/core/ecs/component/registry.hpp
core/include/cubos/core/ecs/world.hpp
core/samples/ecs/general/main.cpp
core/src/cubos/core/ecs/component/manager.cpp
core/src/cubos/core/ecs/component/registry.cpp
core/src/cubos/core/ecs/world.cpp
core/tests/ecs/blueprint.cpp
core/tests/ecs/registry.cpp
core/tests/ecs/world.cpp
engine/include/cubos/engine/scene/bridge.hpp
engine/samples/scene/assets/main.cubos
engine/samples/scene/assets/sub.cubos
engine/src/cubos/engine/scene/bridge.cpp
tools/quadrados-gen/src/main.cpp

Makes the ECS use the actual type name to identify components instead of the attribute name - still haven't removed it from quadrados, but the whole attribute will soon go away anyway. 
Changes the `SceneBridge` to use the new `JSONDeserializer` instead of the old one.

Remove old serialization code from `SceneBridge`

---

tools/tesseratos/CMakeLists.txt
tools/tesseratos/include/tesseratos/asset_explorer/popup.hpp
tools/tesseratos/src/tesseratos/asset_explorer/popup.cpp

~Blocked by #795~
Add a popup function for selecting an asset of a given type, via `popup.hpp & cpp` . This PR only implements the function, and not the usage in the plugins (like scene editor, etc)

Add a popup for selecting an asset of a given type

---

core/include/cubos/core/io/window.hpp
core/src/cubos/core/io/window.cpp
engine/include/cubos/engine/input/action.hpp
engine/include/cubos/engine/input/input.hpp
engine/samples/input/assets/sample.bind
engine/samples/input/main.cpp
engine/samples/input/page.md
engine/src/cubos/engine/input/action.cpp
engine/src/cubos/engine/input/bindings.cpp
engine/src/cubos/engine/input/input.cpp

Adds support for binding mouse buttons to input actions, similar to existing implementation of keyboard/gamepad. Serialization functions are also implemented in order to support adding bindings in an asset.
Adds a new showcase to the input sample to test the bindings.

Add mouse button bindings

---

core/include/cubos/core/ecs/component/manager.hpp
core/include/cubos/core/ecs/component/registry.hpp
core/include/cubos/core/ecs/component/storage.hpp
core/include/cubos/core/ecs/resource/manager.hpp
core/include/cubos/core/ecs/system/commands.hpp
core/include/cubos/core/ecs/system/system.hpp
core/include/cubos/core/ecs/world.hpp
core/src/cubos/core/ecs/component/manager.cpp
core/src/cubos/core/ecs/world.cpp
core/src/cubos/core/gl/ogl_render_device.cpp
core/tests/ecs/blueprint.cpp
core/tests/ecs/registry.cpp
core/tests/ecs/world.cpp
engine/src/cubos/engine/scene/bridge.cpp

Removes all `data::old::Package` related code from the ECS, which is not needed anymore after adding reflection and allowing access to the components through `World`.
Fixed a small unrelated bug introduced in #830, where I forgot to update the format string of the OpenGL message callback.

Remove `[un]packs` from the ECS

---

core/CMakeLists.txt
core/include/cubos/core/reflection/type_registry.hpp
core/src/cubos/core/reflection/type.cpp
core/src/cubos/core/reflection/type_registry.cpp
core/tests/CMakeLists.txt
core/tests/reflection/type.cpp
core/tests/reflection/type_registry.cpp

Adds a `TypeRegistry` utility class, used to keep a set of types which can be queried by their name.
Will be useful to reduce code duplication in #848.

feat(reflection): add TypeRegistry

---

core/include/cubos/core/ecs/world.hpp
core/src/cubos/core/ecs/world.cpp

Adds an untyped version of `World::registerComponent`.

Allow registering components whose type is unknown at compile time

---

core/include/cubos/core/ecs/component/manager.hpp
core/include/cubos/core/ecs/world.hpp
core/src/cubos/core/ecs/component/manager.cpp
core/src/cubos/core/ecs/world.cpp
engine/include/cubos/engine/scene/bridge.hpp
engine/src/cubos/engine/scene/bridge.cpp
engine/src/cubos/engine/scene/plugin.cpp

Adds a getter to the `World` to access the registered component types.
Changes the `SceneBridge` to fetch those types from the `World` instead of the global registry, which will be nuked in the next PR.

Swap global component registry for a world registry

---

core/include/cubos/core/io/window.hpp
core/src/cubos/core/io/glfw_window.cpp
core/src/cubos/core/io/glfw_window.hpp
engine/src/cubos/engine/imgui/imgui.cpp
engine/src/cubos/engine/imgui/imgui.hpp
engine/src/cubos/engine/imgui/plugin.cpp

Adds a setting to change the scale of ImGui elements, allowing them to be displayed at a larger size. Mainly important for screens with high pixel density, where the normal scale looks tiny. Defaults to the OS's DPI scale setting.

Add DPI scaling to ImGui

---

CMakeLists.txt

Add a different path where cmake will look for the ccache binary when it doesn't find it in the default one.

Add support for ccache when using MSYS

---

core/CMakeLists.txt
core/include/cubos/core/ecs/relation/module.dox
core/include/cubos/core/ecs/relation/reflection.hpp
core/include/cubos/core/ecs/relation/table.hpp
core/src/cubos/core/ecs/relation/reflection.cpp
core/src/cubos/core/ecs/relation/table.cpp
core/src/cubos/core/memory/any_vector.cpp
core/tests/CMakeLists.txt
core/tests/ecs/relation/table.cpp
core/tests/ecs/relation/utils.cpp
core/tests/ecs/relation/utils.hpp

Adds `RelationTypeBuilder`, used to make relation type reflection easier.
Adds `RelationTable`. For now, this isn't used anywhere but it will be used in future PRs the store relations which are frequently inserted and removed, such as collision pairs. Read the class documentation for details on how its implemented.

Add `RelationTable`

---

.github/workflows/clang-tidy-lint.yml

Attempts to fix the static analysis CI action.

fix(ci): bump libc from 3.4 to 3.5

---

engine/CMakeLists.txt
engine/include/cubos/engine/screenpicker/plugin.hpp
engine/include/cubos/engine/screenpicker/screenpicker.hpp
engine/src/cubos/engine/screenpicker/plugin.cpp
engine/src/cubos/engine/screenpicker/screenpicker.cpp

Adds a new plugin in `cubos::engine`, which adds the resource `ScreenPicker`. This resource provides a texture with entity/gizmo IDs for mouse picking.

Add screenPickerPlugin

---

core/include/cubos/core/ecs/query/data.hpp
core/include/cubos/core/ecs/query/fetcher.hpp
core/include/cubos/core/ecs/query/filter.hpp
core/include/cubos/core/ecs/query/term.hpp
core/include/cubos/core/ecs/system/query.hpp
core/include/cubos/core/ecs/table/sparse_relation/table.hpp
core/samples/ecs/relations/main.cpp
core/src/cubos/core/ecs/query/filter.cpp
core/src/cubos/core/ecs/query/term.cpp
core/src/cubos/core/ecs/table/sparse_relation/registry.cpp
core/src/cubos/core/ecs/table/sparse_relation/table.cpp
core/src/cubos/core/ecs/types.cpp
core/src/cubos/core/ecs/world.cpp
core/tests/ecs/query/filter.cpp
core/tests/ecs/query/term.cpp
core/tests/ecs/utils.hpp
core/tests/ecs/world.cpp

Changes the query code to allow querying over a single relation and two targets.
Also allows pinning one or both of the targets so that users can query, for example, all of the children of a specific entity.

Allow querying over entity relations

---

core/include/cubos/core/ecs/table/sparse_relation/table.hpp
core/src/cubos/core/ecs/table/sparse_relation/table.cpp
core/src/cubos/core/ecs/world.cpp
core/tests/ecs/table/sparse_relation/table.cpp
core/tests/ecs/world.cpp

I forgot to move relations between tables when their entity's archetypes change.
This adds a test to cover that scenario and fixes the bug.

Move relations to other tables when the archetype changes 

---

core/include/cubos/core/ecs/query/filter.hpp
core/include/cubos/core/ecs/reflection.hpp
core/include/cubos/core/ecs/table/sparse_relation/registry.hpp
core/include/cubos/core/ecs/types.hpp
core/src/cubos/core/ecs/query/filter.cpp
core/src/cubos/core/ecs/types.cpp
core/src/cubos/core/ecs/world.cpp
core/tests/ecs/query/filter.cpp
core/tests/ecs/types.cpp
core/tests/ecs/utils.cpp
core/tests/ecs/utils.hpp

Blocked on #888.
Adds the `SymmetricTrait` which can be added to relation types, making their direction not matter.
This will be useful for relations like `CollidesWith`.

Add symmetric entity relations

---

engine/src/cubos/engine/gizmos/renderer.cpp

Replaces GLSL reserved word "output" in gizmos id shader with "idOutput" (same as the screen picking shader).

Replace reserved keyword in Gizmos shader

---

CMakeLists.txt
engine/include/cubos/engine/physics/resources/fixed_delta_time.hpp
engine/include/cubos/engine/physics/resources/gravity.hpp
engine/include/cubos/engine/physics/resources/substeps.hpp
engine/src/cubos/engine/assets/asset.cpp
engine/src/cubos/engine/assets/assets.cpp
engine/src/cubos/engine/collisions/plugin.cpp

This branch will contain every dirty hack we deem necessary to make a game for DevGamm.
This will hurt :(

DevGamm hacks

---

core/include/cubos/core/ecs/system/system.hpp
core/src/cubos/core/ecs/system/system.cpp
core/tests/ecs/system.cpp
engine/src/cubos/engine/gizmos/plugin.cpp
tools/tesseratos/include/tesseratos/entity_selector/plugin.hpp
tools/tesseratos/src/tesseratos/entity_selector/plugin.cpp

Provides the entitySelector plugin for Tesseratos, which reacts to mouse clicks and sets the currently selected entity to the entity at the clicked coords, using ScreenPicker. Also provides some fixes needed for the plugin to work.

Add entitySelectorPlugin

---

engine/include/cubos/engine/physics/components/force.hpp
engine/include/cubos/engine/physics/components/impulse.hpp
engine/include/cubos/engine/physics/components/mass.hpp
engine/include/cubos/engine/physics/components/velocity.hpp
engine/include/cubos/engine/physics/plugin.hpp
engine/include/cubos/engine/physics/plugins/gravity.hpp
engine/samples/physics/main.cpp
engine/src/cubos/engine/physics/gravity.cpp
engine/src/cubos/engine/physics/plugin.cpp

Separate physics force and impulse into their own components.
Remove Physics prefix from physics force, impulse, velocity and mass components

Separate physics force and impulse into their own components

---

CHANGELOG.md
engine/include/cubos/engine/gizmos/gizmos.hpp
engine/include/cubos/engine/gizmos/plugin.hpp
engine/src/cubos/engine/gizmos/gizmos.cpp
engine/src/cubos/engine/gizmos/plugin.cpp
engine/src/cubos/engine/gizmos/renderer.cpp
engine/src/cubos/engine/gizmos/renderer.hpp
engine/src/cubos/engine/screen_picker/screen_picker.cpp
tools/tesseratos/src/tesseratos/entity_selector/plugin.cpp

Changes gizmosPlugin to store gizmo ids in screenPickerPlugin instead of a separate buffer.

Integrate screenPickerPlugin with gizmosPlugin

---

CHANGELOG.md
engine/include/cubos/engine/imgui/data_inspector.hpp
engine/samples/imgui/main.cpp
engine/src/imgui/data_inspector.cpp
tools/tesseratos/src/tesseratos/entity_inspector/plugin.cpp
tools/tesseratos/src/tesseratos/settings_inspector/plugin.cpp

Modifies `DataInspector` to show/edit the contents of a value without a tree node, allowing for more flexibility outside it.
Adds add/remove component buttons to `EntityInspector`.

Allow adding and removing components on the entity inspector

---

CHANGELOG.md
engine/src/renderer/plugin.cpp

fix(rendering): skip null renderable grids

---

CHANGELOG.md
engine/include/cubos/engine/gizmos/gizmos.hpp
engine/src/gizmos/gizmos.cpp
tools/tesseratos/CMakeLists.txt
tools/tesseratos/include/tesseratos/collider_gizmos/plugin.hpp
tools/tesseratos/src/tesseratos/collider_gizmos/plugin.cpp
tools/tesseratos/src/tesseratos/plugin.cpp

Adds an overload for `drawWireBox` which allows the caller to specify the box rotation.
Adds a new tesseratos plugin `colliderGizmosPlugin` which allows viewing all colliders through the gizmos plugin or only the selected entity.

Collider gizmos

---

CHANGELOG.md
core/include/cubos/core/ecs/cubos.hpp
core/src/ecs/cubos.cpp
tools/tesseratos/CMakeLists.txt
tools/tesseratos/include/tesseratos/play_pause/plugin.hpp
tools/tesseratos/src/tesseratos/play_pause/plugin.cpp
tools/tesseratos/src/tesseratos/plugin.cpp

Adds a multiplier field to the delta time resource and a new tesseratos plugin which allows modifying it.

Add delta time modifier and play/pause plugin

---

engine/src/physics/plugin.cpp

Remove `PhysicsBundle` component when finished unpacking

---

CHANGELOG.md
core/include/cubos/core/ecs/system/dispatcher.hpp
core/src/ecs/cubos.cpp
core/src/ecs/system/dispatcher.cpp
core/tests/ecs/dispatcher.cpp

Stores the received system names in the dispatcher and prints them after compiling the chain.

Log system order on dispatcher

---

CHANGELOG.md
core/include/cubos/core/ecs/cubos.hpp
core/include/cubos/core/ecs/system/dispatcher.hpp
core/src/ecs/cubos.cpp
core/src/ecs/system/dispatcher.cpp
core/tests/ecs/dispatcher.cpp

Adds the `.noTag` and `.noStartupTag` methods to `Cubos`, analogs to `.tag` and `.startupTag` but which can be used to apply configuration to all systems except the ones with the given tag. This was implemented by simply storing the negative tag settings on the same tag name prefixed with '!'. Then, when we apply the tag settings to the systems, we first add the tags `!x` to the system if they're not tagged with `x`.

feat(ecs): add negative tags

---

CHANGELOG.md
engine/include/cubos/engine/transform/local_to_world.hpp
engine/src/transform/local_to_world.cpp
tools/tesseratos/src/tesseratos/transform_gizmo/plugin.cpp

1002 add world positionrotationscale getters to localtoworld

---

CHANGELOG.md
core/include/cubos/core/ecs/system/arguments/query.hpp
tools/tesseratos/samples/main/assets/scenes/main.cubos
tools/tesseratos/src/tesseratos/world_inspector/plugin.cpp

Show childof hierarchy on the world inspector

---

CHANGELOG.md
engine/src/gizmos/types/cut_cone.hpp
engine/src/gizmos/types/ring.hpp
tools/tesseratos/include/tesseratos/transform_gizmo/plugin.hpp
tools/tesseratos/src/tesseratos/transform_gizmo/plugin.cpp

Adds Rotation Gizmo, fixes a bug, and adds a toggle for global/local axis

878 add rotation gizmo

---

engine/include/cubos/engine/transform/rotation.hpp
engine/src/transform/rotation.cpp

Adds a static method `Rotation::lookingAt`, which returns a new `Rotation` component looking in the given direction.

feat(transform): add Rotation::lookingAt

---

core/include/cubos/core/ecs/system/arguments/commands.hpp
core/src/ecs/system/arguments/commands.cpp
core/tests/ecs/commands.cpp

Can be used to give names to entities more easily.
Just shortened `.add(Name{"foo})` for `.named("foo")`.

feat(ecs): add Commands::EntityBuilder::named

---

CHANGELOG.md
engine/src/renderer/deferred_renderer.cpp

Fixes a renderer crash when we creating empty voxel grids.

Fix crash on empty grid

---

CHANGELOG.md
engine/CMakeLists.txt
engine/include/cubos/engine/render/module.dox
engine/include/cubos/engine/render/shader/bridge.hpp
engine/include/cubos/engine/render/shader/plugin.hpp
engine/include/cubos/engine/render/shader/shader.hpp
engine/src/render/shader/bridge.cpp
engine/src/render/shader/plugin.cpp
engine/src/render/shader/shader.cpp

Adds a new `shaderPlugin`, which registers a new `ShaderBridge`, and assets of the `Shader` type, which contain a `cubos::core::gl::ShaderStage`, created from a file's GLSL code.

Add Shader asset and bridge

---

.github/workflows/clang-tidy-lint.yml
CHANGELOG.md
core/CMakeLists.txt
core/include/cubos/core/ecs/blueprint.hpp
core/include/cubos/core/ecs/cubos.hpp
core/include/cubos/core/ecs/query/fetcher.hpp
core/include/cubos/core/ecs/system/arguments/commands.hpp
core/include/cubos/core/ecs/types.hpp
core/include/cubos/core/ecs/world.hpp
core/include/cubos/core/log.hpp
core/include/cubos/core/memory/type_map.hpp
core/include/cubos/core/reflection/reflect.hpp
core/include/cubos/core/reflection/type.hpp
core/include/cubos/core/reflection/type_registry.hpp
core/samples/logging/main.cpp
core/samples/reflection/traits/enum/main.cpp
core/samples/reflection/traits/mask/main.cpp
core/src/log.cpp
core/src/reflection/reflect.cpp
core/src/reflection/type.cpp
core/tests/data/des/json.cpp
core/tests/data/ser/debug.cpp
core/tests/data/ser/json.cpp
core/tests/reflection/comparison.cpp
core/tests/reflection/reflect.cpp
core/tests/reflection/traits/enum.cpp
core/tests/reflection/traits/fields.cpp
core/tests/reflection/traits/mask.cpp
engine/include/cubos/engine/assets/asset.hpp

Splits the reflect method into get and make.
Will be necessary to import and export types correctly from shared libraries later on. This way, if the class is being imported, the reflection type is also being imported, instead of a duplicate being created.
Also changes `reflect` to work for types which don't implement reflection, in which case it returns an unnamed type with an empty `ConstructibleTrait`.

Split reflect method into two and implement automatic empty reflection for non-implemented types

---

CHANGELOG.md
engine/CMakeLists.txt
engine/include/cubos/engine/render/g_buffer/g_buffer.hpp
engine/include/cubos/engine/render/g_buffer/plugin.hpp
engine/include/cubos/engine/render/target/target.hpp
engine/src/render/g_buffer/g_buffer.cpp
engine/src/render/g_buffer/plugin.cpp

Adds the `gBufferPlugin`, which adds and manages the `GBuffer` component.
Also adds a placeholder `RenderTarget` component to make this implementable (still missing the actual plugin and logic).

Add GBuffer plugin

---

CHANGELOG.md
core/src/memory/any_vector.cpp

Turns out some components were being destroyed twice, which led to a double free error, due to a bug in AnyVector::swapErase.

Fix AnyVector::swapErase double destroy

---

CHANGELOG.md
engine/src/imgui/data_inspector.cpp

It wasn't being checked, and thus the program crashed sometimes when you scrolled past stuff which used the data inspector.

fix(imgui): handle BeginTable return value on DataInspector

---

CHANGELOG.md
core/include/cubos/core/io/window.hpp
core/samples/gl/compute/main.cpp
core/samples/gl/debug_renderer/main.cpp
core/samples/gl/quad/main.cpp
core/src/io/glfw_window.cpp
core/src/io/glfw_window.hpp
engine/CMakeLists.txt
engine/include/cubos/engine/render/g_buffer/plugin.hpp
engine/include/cubos/engine/render/target/plugin.hpp
engine/src/render/g_buffer/plugin.cpp
engine/src/render/target/plugin.cpp
engine/src/render/target/target.cpp

Adds a new `renderTargetPlugin` in the `cubos/engine/render` directory, which registers a new component named `RenderTarget`, and a system which automatically resizes render targets with a null framebuffer to the current window size.
Also changes window `framebufferSize()` and `size()` return types to unsigned values, because the window size shouldn't be negative.

Add Render Target plugin

---

CHANGELOG.md
engine/CMakeLists.txt
engine/include/cubos/engine/render/picker/picker.hpp
engine/include/cubos/engine/render/picker/plugin.hpp
engine/src/render/picker/picker.cpp
engine/src/render/picker/plugin.cpp

Adds a `renderPickerPlugin` in the `cubos/engine/render` directory, which registers a component named `RenderPicker`, and a system which automatically resizes render picker textures when the corresponding render target is resized.
This should do the same as the existing `screenPickerPlugin` and `ScreenPicker`, but uses the new `RenderTarget`.

Add Render Picker plugin

---

CHANGELOG.md
core/CMakeLists.txt
core/include/cubos/core/thread/module.dox
core/include/cubos/core/thread/pool.hpp
core/include/cubos/core/thread/task.hpp
core/src/thread/pool.cpp
core/src/thread/task.cpp
core/tests/CMakeLists.txt
core/tests/thread/task.cpp

Utility class which can be used to wait for results which come from asynchronous code.
This will be really useful to implement stuff like waiting for a given voxel object to be loaded and meshed, instead of just blocking the entire application. With this we'll able to implement stuff like smooth terrain loading and loading screens.
Since this doesn't really fit in the other existing modules, created a new dir `core/thread` and also moved the thread pool class there.

Add threading Tasks

---

CHANGELOG.md
engine/CMakeLists.txt
engine/include/cubos/engine/render/camera/draws_to.hpp
engine/include/cubos/engine/render/camera/perspective_camera.hpp
engine/include/cubos/engine/render/camera/plugin.hpp
engine/src/render/camera/draws_to.cpp
engine/src/render/camera/perspective_camera.cpp
engine/src/render/camera/plugin.cpp

Add a new `cameraPlugin`, which adds the `PerspectiveCamera` component (same fields as old `Camera`, plus a new `active` field to support multiple cameras per `RenderTarget`) and the `DrawsTo` relation, which has no fields.

Add Camera plugin

---

CHANGELOG.md
core/CMakeLists.txt
core/include/cubos/core/ecs/cubos.hpp
core/include/cubos/core/ecs/module.dox
core/include/cubos/core/ecs/plugin_queue.hpp
core/include/cubos/core/ecs/system/arguments/plugins.hpp
core/include/cubos/core/ecs/system/fetcher.hpp
core/include/cubos/core/ecs/system/planner.hpp
core/include/cubos/core/ecs/table/sparse_relation/registry.hpp
core/include/cubos/core/ecs/table/sparse_relation/table.hpp
core/include/cubos/core/ecs/types.hpp
core/include/cubos/core/ecs/world.hpp
core/src/ecs/cubos.cpp
core/src/ecs/observer/observers.cpp
core/src/ecs/plugin_queue.cpp
core/src/ecs/system/arguments/plugins.cpp
core/src/ecs/system/planner.cpp
core/src/ecs/table/sparse_relation/registry.cpp
core/src/ecs/table/sparse_relation/table.cpp
core/src/ecs/types.cpp
core/src/ecs/world.cpp
core/tests/ecs/cubos.cpp
core/tests/ecs/types.cpp
engine/include/cubos/engine/prelude.hpp

Blocked on #1117.
Adds a new system argument `Plugins`, through which systems can add and remove plugins at runtime.
When a new plugin is added, its startup systems are run before starting the next frame.
Its main systems are added to the existing schedule.
When removing a plugin, all of its resources, components, relations, tags, systems are removed.
Any created entity remains, but without the removed component types.

Allow uninstalling and installing plugins dynamically

---

CHANGELOG.md
engine/CMakeLists.txt
engine/assets/render/deferred_shading.fs
engine/assets/render/ssao_base.fs
engine/assets/render/ssao_blur.fs
engine/include/cubos/engine/render/camera/draws_to.hpp
engine/include/cubos/engine/render/split_screen/plugin.hpp
engine/include/cubos/engine/render/split_screen/split_screen.hpp
engine/samples/render/assets/main.cubos
engine/samples/render/main.cpp
engine/src/render/camera/draws_to.cpp
engine/src/render/deferred_shading/plugin.cpp
engine/src/render/g_buffer_rasterizer/plugin.cpp
engine/src/render/split_screen/plugin.cpp
engine/src/render/split_screen/split_screen.cpp
engine/src/render/ssao/plugin.cpp

Ports the splitscreen plugin to the new renderer. For each `DrawsTo` relation with a target that has a `SplitScreen` component, the plugin sets the viewport in the relation. Plugins which draw to the target should use this viewport.

Add split screen to new renderer

---

core/include/cubos/core/ecs/query/opt.hpp
docs/pages/3_examples/2_engine/main.md
engine/CMakeLists.txt
engine/assets/ui/color_rect.fs
engine/assets/ui/element.vs
engine/include/cubos/engine/ui/canvas/draw_list.hpp
engine/include/cubos/engine/ui/canvas/element.hpp
engine/include/cubos/engine/ui/canvas/plugin.hpp
engine/include/cubos/engine/ui/color_rect/plugin.hpp
engine/include/cubos/engine/ui/module.dox
engine/samples/ui/main.cpp
engine/src/ui/canvas/draw_list.cpp
engine/src/ui/canvas/element.cpp
engine/src/ui/canvas/plugin.cpp
engine/src/ui/color_rect/plugin.cpp

The two main UI components are UIElement and UICanvas.
For it to work properly, each UIElement must be a child of a UICanvas, or of another UIElement.
Each UIElement generates a list of drawing commands, UIDrawList, that are then pooled together by the UICanvas at the root of the hierarchy.
Each entry in a draw list contains a UIDrawList::Type and a UIDrawList::Command. The Type holds information that is common for all similar commands, and the Command contains the specifics to that one command.
Each entry also has a raw data buffer to hold the data the command needs to pass to the shaders.
After aggregating the draw commands, the UICanvas draws them, grouped by type.

feat(ui): draw ui through commands

---

CHANGELOG.md
core/include/cubos/core/log.hpp
core/samples/logging/main.cpp
core/samples/logging/page.md
core/src/ecs/system/tag.cpp
core/src/log.cpp

The implementation is: when logging (with cubos_debug, etc..), if the file was set, it also prints to the file stream.
this means: data logged before setting the file, wont be logged

Implement file logging

---

CHANGELOG.md
CMakeLists.txt
api/CMakeLists.txt
api/core/CMakeLists.txt
api/core/include/cubos/api/core/api.h
api/core/include/cubos/api/core/module.dox
api/core/samples/CMakeLists.txt
api/core/src/api.cpp
api/engine/CMakeLists.txt
api/engine/include/cubos/api/engine/api.h
api/engine/include/cubos/api/engine/module.dox
api/engine/samples/CMakeLists.txt
api/engine/src/api.cpp
core/include/cubos/core/log.hpp
core/samples/logging/main.cpp
core/samples/logging/page.md
core/src/ecs/system/tag.cpp
core/src/log.cpp
docs/Doxyfile

Creates a new directory `api/` with two projects for the core and engine C API libraries. Both have their own CMakeLists.txt file and a samples directory which will probably be needed later for testing these new libraries.

Setup file structure and cmake for the core and engine API libraries

---

CHANGELOG.md
core/include/cubos/core/ecs/cubos.hpp
core/src/ecs/cubos.cpp

Splits the existing run method into two methods, `start` and `update`:
- `start` initializes the application and runs the startup systems;
- `update` runs the main systems once, and returns whether the application has finished.
This is necessary for the standalone Tesseratos app, as we need to be able to run a single frame of the game inside a system of the Tesseratos application. This will probably look something like:
```cpp
cubos.system("update Game").call([](Game& game) {
if (!game.paused)
{
if (!game.cubos.update())
{
// Game stopped
}
}
});
```

feat(ecs): add Cubos::start and Cubos::update

---

CHANGELOG.md
core/include/cubos/core/ecs/cubos.hpp
core/src/ecs/cubos.cpp
core/tests/ecs/cubos.cpp

Adds a method to the `Cubos` class which allows the dev to inject a plugin into another plugin's place.
This will be useful to make Tesseratos a standalone app, as we'll need to make a 'fake window plugin' for the game to run properly - we want the game to be shown within the existing Tesseratos window.
The goal is to be able do this: `game.cubos.inject(windowPlugin, fakeWindowPlugin)`.
Then, when the game calls `cubos.plugin(windowPlugin)`, `fakeWindowPlugin` will be added instead, seamlessly.

feat(ecs): add Cubos::inject

---

CHANGELOG.md
core/CMakeLists.txt
core/include/cubos/core/ecs/blueprint.hpp
core/include/cubos/core/ecs/dynamic.hpp
core/include/cubos/core/ecs/name.hpp
core/include/cubos/core/ecs/plugin_queue.hpp
core/include/cubos/core/ecs/types.hpp
core/src/ecs/dynamic.cpp

This is the first step towards having a standalone editor application!
This PR just adds a new class, `DynamicPlugin`, which is used to load shared libraries and import plugins from them, in a cross-platform manner.
For example, you could do something like:
```cpp
DynamicPlugin plugin{};
plugin.load("game.dll"); // would have a different name in linux, probably "game.so" or smth
cubos.plugin(plugin.function());
```
This isn't meant to be used directly by the user - it will be mostly used internally by the Tesseratos application.
Also included a small commit adding some missing `@ingroup` tags.

Allow importing plugins from shared libraries

---

CHANGELOG.md
core/include/cubos/core/gl/render_device.hpp
core/src/gl/ogl_render_device.cpp
core/src/gl/ogl_render_device.hpp
core/src/gl/render_device.cpp

Adds a Timer to RenderDevice, which exposes OpenGL queries to allow profiling sections of rendering code. Also adds an higher-level PipelinedTimer for profiling every frame asynchronously.

Add core::gl::Timer

---

CHANGELOG.md
core/CMakeLists.txt
core/include/cubos/core/ecs/cubos.hpp
core/include/cubos/core/ecs/query/data.hpp
core/include/cubos/core/ecs/query/fetcher.hpp
core/include/cubos/core/ecs/system/arguments/query.hpp
core/include/cubos/core/ecs/system/planner.hpp
core/include/cubos/core/ecs/system/schedule.hpp
core/include/cubos/core/memory/opt.hpp
core/src/ecs/cubos.cpp
core/src/ecs/query/opt.cpp
core/src/ecs/system/planner.cpp
core/src/ecs/system/schedule.cpp
core/src/memory/opt.cpp
core/tests/ecs/query.cpp
core/tests/ecs/system/schedule.cpp
engine/include/cubos/engine/prelude.hpp
engine/include/cubos/engine/render/defaults/target.hpp
engine/src/render/defaults/target.cpp
tools/tesseratos/src/tesseratos/transform_gizmo/plugin.cpp
tools/tesseratos/src/tesseratos/world_inspector/plugin.cpp

Move `Opt` class from `ecs` to `memory` namespace.

Move Opt class to memory namespace

---

CHANGELOG.md
core/CMakeLists.txt
core/include/cubos/core/net/address.hpp
core/src/net/address.cpp
core/tests/CMakeLists.txt
core/tests/net/address.cpp

blocked by #1259 
Add a network `Address` class, as proposed in the issue.

Add network Address class

---

CHANGELOG.md
core/include/cubos/core/io/keyboard.hpp
core/include/cubos/core/io/window.hpp
core/src/data/ser/debug.cpp
core/src/io/glfw_window.cpp
core/src/io/glfw_window.hpp
core/src/io/keyboard.cpp
engine/CMakeLists.txt
engine/include/cubos/engine/input/action.hpp
engine/include/cubos/engine/input/axis.hpp
engine/include/cubos/engine/input/combination.hpp
engine/include/cubos/engine/input/input.hpp
engine/samples/collisions/main.cpp
engine/samples/games/cubosurfers/assets/input.bind
engine/samples/input/assets/sample.bind
engine/samples/input/main.cpp
engine/src/input/action.cpp
engine/src/input/axis.cpp
engine/src/input/combination.cpp
engine/src/input/input.cpp
flake.nix
tools/tesseratos/assets/tesseratos.bind

Depends on #1278 
Introduces InputCombinations to replace KeyWithModifiers
Also closes #1279 
Did not test if gamepad was broken with the changes

Track key combos instead of keys with modifiers

---

.github/workflows/clang-tidy-lint.yml

The action fails while trying to dismiss the reviews, might as well disable the request changes feature.
Note that this doesn't mean disabling the comments, the comments are still there.

fix(ci): do not request changes on clang-tidy-lint.yml

---

CHANGELOG.md
engine/include/cubos/engine/physics/components/physics_material.hpp
engine/include/cubos/engine/physics/physics_bundle.hpp
engine/include/cubos/engine/physics/plugin.hpp
engine/samples/complex_physics/assets/scenes/red_cube.cubos
engine/samples/complex_physics/assets/scenes/white_cube.cubos
engine/samples/complex_physics/main.cpp
engine/src/physics/plugin.cpp
engine/src/physics/solver/penetration_constraint/plugin.cpp

Add PhysicsMaterial component which allows to customize the behaviour of physics objects by changing their friction coefficient and bounciness. How the values of each are mixed to determine the value to use in the collision resolution can also be customized by choosing between 4 methods, which are some of the most common methods found online. This is inspired by Unity and Unreal which also do this. What the best is will depend on the use case, so I believe that this is better than only letting 1 method.
What some use (restitution only): https://stackoverflow.com/questions/1678908/applying-coefficient-of-restitution-in-a-collision-resolution-method
Unity: https://docs.unity3d.com/Manual/collider-surfaces-combine.html
Unreal: https://dev.epicgames.com/documentation/en-us/unreal-engine/physic …

Physics Materials

---

CHANGELOG.md
engine/include/cubos/engine/collisions/shapes/box.hpp
engine/include/cubos/engine/physics/components/angular_impulse.hpp
engine/include/cubos/engine/physics/components/angular_velocity.hpp
engine/include/cubos/engine/physics/components/center_of_mass.hpp
engine/include/cubos/engine/physics/components/force.hpp
engine/include/cubos/engine/physics/components/impulse.hpp
engine/include/cubos/engine/physics/components/inertia.hpp
engine/include/cubos/engine/physics/components/mass.hpp
engine/include/cubos/engine/physics/components/torque.hpp
engine/include/cubos/engine/physics/physics_bundle.hpp
engine/include/cubos/engine/physics/plugin.hpp
engine/samples/complex_physics/assets/scenes/red_cube.cubos
engine/samples/complex_physics/assets/scenes/white_cube.cubos
engine/src/collisions/interface/shapes/box.cpp
engine/src/physics/plugin.cpp
engine/src/physics/solver/plugin.cpp

Add components for torque, angular impulse, inertia, angular velocity and center of mass.
Add ability to add force or impulse on a point of the object, for this we changed the Force and Impulse components, which now also hold a torque and angular impulse, respectively.
Reference: https://research.ncl.ac.uk/game/mastersdegree/gametechnologies/physicstutorials/3angularmotion/Physics%20-%20Angular%20Motion.pdf

Add components to support rigid body rotation

---

CHANGELOG.md
engine/src/render/deferred_shading/plugin.cpp

Changes `spotAngle` and `innerSpotAngle` to match the total angle between lateral edges of the spot light, instead of the angle between each edge and the center. This is more intuitive and matches the way shadow rendering already used these values.

Change spot light angles to match the angle between edges

---

CHANGELOG.md
engine/include/cubos/engine/physics/components/inertia.hpp
engine/src/physics/plugin.cpp
engine/src/physics/solver/integration/plugin.cpp

Apply torque and angular impulses on integration to rotate the bodies.
Resources: https://research.ncl.ac.uk/game/mastersdegree/gametechnologies/physicstutorials/3angularmotion/Physics%20-%20Angular%20Motion.pdf

Add rotation to integration

---

CHANGELOG.md
engine/src/render/deferred_shading/plugin.cpp
engine/src/render/shadow_atlas_rasterizer/plugin.cpp

Fixes spot lights being "cut" before the maximum range is reached, when shadows are used on a spot light with global scale lower than 1.

Fix spot light range cutoff when using shadows

---

CHANGELOG.md
core/CMakeLists.txt
core/include/cubos/core/data/des/binary.hpp
core/include/cubos/core/data/ser/binary.hpp
core/src/data/des/binary.cpp
core/src/data/ser/binary.cpp
core/tests/CMakeLists.txt
core/tests/data/serdes/binary.cpp

Adds both the `BinarySerializer` and `BinaryDeserializer` classes, which will be useful for communication between the editor and the game - saves time and memory in comparison with the existing JSON classes.

Add Binary Serializer and Deserializer

---

CHANGELOG.md
engine/include/cubos/engine/input/axis.hpp
engine/src/input/axis.cpp

A deadzone was added to input axis, so there's no need to filter the noise manually.

feat(input): add deadzone to axis

---

CHANGELOG.md
core/CMakeLists.txt
core/include/cubos/core/ecs/cubos.hpp
core/include/cubos/core/memory/opt.hpp
core/src/data/des/binary.cpp
core/src/data/ser/binary.cpp
core/src/ecs/cubos.cpp
core/src/ecs/debugger.cpp
core/src/ecs/debugger.hpp
engine/samples/assets/bridge/main.cpp
engine/samples/assets/json/main.cpp
engine/samples/assets/saving/main.cpp
engine/samples/collisions/main.cpp
engine/samples/events/main.cpp
engine/samples/games/cubosurfers/main.cpp
engine/samples/hello-cubos/main.cpp
engine/samples/imgui/main.cpp
engine/samples/input/main.cpp
engine/samples/render/main/main.cpp
engine/samples/render/shadows/main.cpp
tools/tesseratos/CMakeLists.txt
tools/tesseratos/src/tesseratos/asset_explorer/popup.hpp
tools/tesseratos/src/tesseratos/debugger/debugger.cpp
tools/tesseratos/src/tesseratos/debugger/debugger.hpp
tools/tesseratos/src/tesseratos/debugger/plugin.cpp
tools/tesseratos/src/tesseratos/debugger/plugin.hpp
tools/tesseratos/src/tesseratos/main.cpp

Adds remote debugging to Cubos. Basically, the Cubos class now parses its incoming command line arguments.
If `--debug <port>` is passed, then, instead of immediately starting and running the game, it waits for a TCP connection on that port. When a connection is accepted, it listens for commands, such as:
- `run` - makes the application resume running.
- `pause` - makes the application stop and wait for further commands.
- `update <N>` - makes the application run its update systems `N` times.
- `close` - closes the application.
- `disconnect` - closes the connection. The application starts listening again for another connection.
Also adds a simple UI tool to test this functionality inside Tesseratos.

Add initial communication between game and editor

---

.gitmodules
CHANGELOG.md
core/CMakeLists.txt
core/include/cubos/core/log.hpp
core/src/gl/ogl_render_device.cpp
core/src/log.cpp

Adds yet another dependency to the core lib, *cpptrace*.
This one is really necessary - turns out implementing this ourselves is a giant hassle, as there a lot of platform and compiler quirks.
In the future it might no longer be necessary, as C++23 comes with a `<stacktrace>` include - not all compilers support it yet.
To use this, I simply call our own `abort` function, which first prints the stacktrace using `cpptrace`, and then calls the usual `std::abort` function.
The result looks like this:

Show stacktrace on CUBOS_FAIL

---

CHANGELOG.md
engine/include/cubos/engine/collisions/contact_manifold.hpp
engine/include/cubos/engine/physics/physics_bundle.hpp
engine/samples/collisions/main.cpp
engine/samples/complex_physics/assets/scenes/red_cube.cubos
engine/samples/complex_physics/assets/scenes/white_cube.cubos
engine/samples/complex_physics/main.cpp
engine/src/collisions/interface/contact_manifold.cpp
engine/src/collisions/narrow_phase/plugin.cpp
engine/src/physics/constraints/penetration_constraint.cpp
engine/src/physics/constraints/penetration_constraint.hpp
engine/src/physics/plugin.cpp
engine/src/physics/solver/penetration_constraint/plugin.cpp

Adds angular velocity computation in penetration constraint solving.

Add rotation on constraint solving

---

engine/include/cubos/engine/tools/console/plugin.hpp
engine/include/cubos/engine/tools/debug_camera/plugin.hpp
engine/include/cubos/engine/tools/ecs_statistics/plugin.hpp
engine/include/cubos/engine/tools/entity_inspector/plugin.hpp
engine/include/cubos/engine/tools/metrics_panel/plugin.hpp
engine/include/cubos/engine/tools/play_pause/plugin.hpp
engine/include/cubos/engine/tools/plugin.hpp
engine/include/cubos/engine/tools/selection/plugin.hpp
engine/include/cubos/engine/tools/selection/selection.hpp
engine/include/cubos/engine/tools/settings_inspector/plugin.hpp
engine/include/cubos/engine/tools/toolbox/plugin.hpp
engine/include/cubos/engine/tools/toolbox/toolbox.hpp
engine/include/cubos/engine/tools/transform_gizmo/plugin.hpp
engine/include/cubos/engine/tools/world_inspector/plugin.hpp

Turns out in #1324 I forgot to add the CUBOS_ENGINE_API macro to most of the tool functions.
This leads to weird crashes when building with shared libraries enabled (e.g. plugin missing error)
This PR just fixes that.

fix(engine): add missing CUBOS_ENGINE_API to new tool functions

---

CHANGELOG.md
core/CMakeLists.txt
core/include/cubos/core/data/fs/standard_archive.hpp
core/include/cubos/core/thread/process.hpp
core/include/cubos/core/thread/task.hpp
core/src/data/fs/standard_archive.cpp
core/src/thread/process.cpp
core/tests/data/fs/standard_archive.cpp
core/tests/thread/task.cpp
engine/include/cubos/engine/assets/assets.hpp
engine/include/cubos/engine/collisions/shapes/box.hpp
engine/samples/complex_physics/assets/scenes/red_cube.cubos
engine/samples/complex_physics/assets/scenes/white_cube.cubos
engine/samples/games/cubosurfers/assets/scenes/main.cubos
engine/samples/games/cubosurfers/assets/scenes/obstacle.cubos
engine/src/assets/assets.cpp
engine/src/assets/bridges/file.cpp
engine/src/collisions/interface/shapes/box.cpp
tools/tesseratos/CMakeLists.txt
tools/tesseratos/src/tesseratos/debugger/plugin.hpp
tools/tesseratos/src/tesseratos/main.cpp
tools/tesseratos/src/tesseratos/project/manager.cpp
tools/tesseratos/src/tesseratos/project/manager.hpp
tools/tesseratos/src/tesseratos/project/plugin.cpp
tools/tesseratos/src/tesseratos/project/plugin.hpp

Adds the project plugin, which adds support for the `ProjectManager` system argument, along with an ImGui window for opening and closing projects + launching them and terminating them.
Also adds an utility class Process to the core to handle multiple processes in a cross-platform way.
There are also some other random fixes or simple methods that I needed to add to other areas in order to make this possible. Looking at the commit history probably gives a better view of what I changed.
**I need people with Windows and MacOS to check if this also works in other operating systems**

Allow opening projects through Tesseratos

---

CHANGELOG.md
core/src/ecs/world.cpp
core/tests/ecs/cubos.cpp

ECS crashes when an onRemove observer makes a change to the entity
- Added test coverage for removing components with onRemove observers that edit their entity.
- Added refetching of archetypes after observers are called

fix(core): Fix ECS onRemove observer bug

---

.github/CODEOWNERS
CHANGELOG.md
engine/assets/render/deferred_shading.fs

Avoid copying light structs in the deferred shading's fragment shader when calling functions, passing an index to the lights array instead.
This fixes the performance issue in #1345.

Avoid copying light structs in deferred shading for performance reasons

---

CHANGELOG.md
core/src/memory/any_vector.cpp

This happened only when the last element of an AnyVector was removed in a swapMove.
The destructor of the last element was called in the swapMove itself, and once again on pop.
So, simply moved the extra destructor call to within the if itself.

fix(memory): prevent double destruction in AnyVector::swapMove

---

CHANGELOG.md
core/src/ecs/query/filter.cpp

Added an assert that mNodeCount is smaller than the array size.
Had to also add some kind of "aliasing" to mNodeCount because the compiler thinks it might be mutated.
```cpp
138   │     int mNodeCount = this->mNodeCount;
139   │     CUBOS_ASSERT(mNodeCount <= QueryNode::MaxCursorCount);
140   │     for (int i = 1; i < mNodeCount; ++i)
141   │     {
142   │         mNodePins[i] = mNodePins[i - 1] | mNodes[i - 1]->pins();
143   │     }
```
- #1351

-O3 flag causes compiler error on ECS QueryFilter

---

CHANGELOG.md
engine/samples/games/cubosurfers/assets/input.bind
engine/src/tools/debug_camera/plugin.cpp

Added a hold function to allow using the debug_camera holding a button as well as a toggle.
Added the input bindings to use the debug_camera on the cubosurfers sample.

1030 rotate debug camera with middle mouse button hold instead of key toggle

---

CHANGELOG.md
core/include/cubos/core/ecs/cubos.hpp

TL;DR the documentation was wrong, ty @SrGesus for the find

docs(ecs): flip SystemBuilder::before and SystemBuilder::after docs

---

CHANGELOG.md
engine/assets/render/deferred_shading.fs
engine/include/cubos/engine/render/shadows/caster.hpp
engine/src/render/deferred_shading/plugin.cpp
engine/src/render/shadows/caster.cpp

I added the Shadow Normal Offset Bias to the deferred shading and gave the user the option to use or not use this bias.

feat(rendering): Add Shadow Normal Offset Bias in the deferred shading

---

CHANGELOG.md
core/src/ecs/query/node/related.cpp
core/src/ecs/world.cpp
core/tests/ecs/query/filter.cpp
core/tests/ecs/utils/action.cpp

I made two fixes on this PR. I added long explanations to the commit messages, if you're curious.

Fix non-deterministic ECS stress test failures

---

CHANGELOG.md
engine/CMakeLists.txt
engine/assets/render/tone_mapping.fs
engine/include/cubos/engine/render/defaults/target.hpp
engine/include/cubos/engine/render/tone_mapping/fxaa.hpp
engine/src/render/defaults/plugin.cpp
engine/src/render/tone_mapping/fxaa.cpp
engine/src/render/tone_mapping/plugin.cpp

Added anti-aliasing using the FXAA technique.
Before
After

feat(anti-aliasing): add anti-aliasing by FXAA

---

CHANGELOG.md
engine/include/cubos/engine/settings/settings.hpp
engine/samples/settings/main.cpp
engine/src/settings/plugin.cpp
engine/src/settings/settings.cpp

feat(settings): add method that saves settings to file

---

CHANGELOG.md
engine/include/cubos/engine/physics/plugin.hpp
engine/include/cubos/engine/physics/resources/solver_constants.hpp
engine/src/physics/plugin.cpp
engine/src/physics/solver/integration/plugin.cpp
engine/src/physics/solver/penetration_constraint/plugin.cpp

Added a resource to easily configure magic numbers in solver.

feat(engine): added resource to easily configure magic numbers in solver

---

CHANGELOG.md
core/include/cubos/core/geom/intersections.hpp
core/include/cubos/core/geom/polygonal_feature.hpp
core/include/cubos/core/geom/utils.hpp
core/src/geom/intersections.cpp
core/src/geom/utils.cpp
engine/include/cubos/engine/collisions/contact_manifold.hpp
engine/samples/collisions/main.cpp
engine/src/collisions/interface/contact_manifold.cpp
engine/src/collisions/narrow_phase/plugin.cpp

Add contact caching for box-box collisions (can't do for voxel before refactor)
- changed when and how the unrelate of the CollidingWith happens
- added a new "shape" type to geom to contain the feature info and the ids
- changed functions to use this ^
- added a new struct to contain the feature id
- added new sections in systems to check if the collisions were already happening in the previous section and if so update them instead of replacing them
This doesn't have warm starting yet, so it looks just like before.
References:
- [https://box2d.org/files/[ErinCatto_IterativeDynamics_GDC2005.pdf](https://box2d.org/files/ErinCatto_IterativeDynamics_GDC2005.pdf)
- Avian/Parry for inspiration on 3D feature IDs

Implement contact caching for box-box collisions

---

CHANGELOG.md
engine/CMakeLists.txt
engine/include/cubos/engine/imgui/context.hpp
engine/include/cubos/engine/imgui/plugin.hpp
engine/samples/imgui/main.cpp
engine/samples/imgui/page.md
engine/src/imgui/context.cpp
engine/src/imgui/plugin.cpp
tools/tesseratos/src/tesseratos/main.cpp

You can read the documentation I included in the PR changes to understand what I'm fixing here.
If you're running Windows, previously with `CUBOS_ENGINE_SHARED` set to `ON` on CMake you probably got a crash on both Tesseratos and on the ImGui sample. With this change, that should no longer happen, so **please test that before approving**.

Fix crash when using ImGui across DLL boundaries on Windows

---

CHANGELOG.md
engine/assets/render/deferred_shading.fs
engine/include/cubos/engine/render/defaults/target.hpp
engine/src/render/defaults/plugin.cpp
engine/src/render/defaults/target.cpp
engine/src/render/deferred_shading/plugin.cpp

Changes deferred shading to work without SSAO. If the SSAO component isn't present in the render target, the feature is disabled.

Make SSAO optional

---

CHANGELOG.md
engine/assets/render/ssao_blur.fs
engine/include/cubos/engine/render/ssao/ssao.hpp
engine/src/render/ssao/plugin.cpp
engine/src/render/ssao/ssao.cpp

Adds a resolution scale value to the SSAO component to adjust the SSAO texture size. The default value of 0.5 provides a good quality with much better performance than full resolution (1.0).

Add SSAO resolution scale

---

.github/workflows/build-doxygen-docs.yml
.github/workflows/build-engine-linux.yml
.github/workflows/build-engine-web.yml
.github/workflows/clang-format-check.yml
.github/workflows/clang-tidy-lint.yml
.github/workflows/conventional-commits.yml
.github/workflows/copy-labels.yml
.github/workflows/create-coverage-report.yml
.github/workflows/preview-docs.yml
CHANGELOG.md
engine/include/cubos/engine/physics/components/angular_impulse.hpp
engine/include/cubos/engine/physics/components/angular_velocity.hpp
engine/include/cubos/engine/physics/components/impulse.hpp
engine/include/cubos/engine/physics/components/velocity.hpp
engine/include/cubos/engine/physics/resources/solver_constants.hpp
engine/samples/complex_physics/main.cpp
engine/src/physics/solver/integration/plugin.cpp
engine/src/physics/solver/penetration_constraint/plugin.cpp
engine/src/physics/solver/penetration_constraint/plugin.hpp

Add warm starting to physics. Takes the impulses applied in the previous frame to apply them at the beggining of the next for increased stability in stacking scenarios.

Add warm starting

---

CHANGELOG.md
engine/CMakeLists.txt
engine/include/cubos/engine/render/shader/shader.hpp
engine/include/cubos/engine/render/shader/shader_builder.hpp
engine/src/render/shader/bridge.cpp
engine/src/render/shader/shader.cpp
engine/src/render/shader/shader_builder.cpp

Adds the ability to configure compile-time shader parameters using `#define` macros. This allows changing e.g. the number of CSM splits in deferred shading, textures drawn to in the G-buffer rasterizer (to disable/enable the render picker).

Add conditional shader compilation

---

docs/pages/3_examples/2_engine/main.md
engine/samples/audio/main.cpp
engine/samples/audio/page.md

Add the link for the audio sample page.

docs: add audio sample page

---

CHANGELOG.md
engine/src/gizmos/plugin.cpp
engine/src/tools/selection/plugin.cpp

This fixes the selection of gizmos on HiDPI screens.

fix(gizmos): fix gizmos selection on HiDPI screens

---

CHANGELOG.md
default.nix
engine/CMakeLists.txt
tools/tesseratos/src/tesseratos/main.cpp

839 stacking layout config for tesseratos

---

engine/include/cubos/engine/collisions/colliding_with.hpp
engine/include/cubos/engine/collisions/contact_manifold.hpp
engine/include/cubos/engine/collisions/shapes/voxel.hpp
engine/samples/collisions/main.cpp
engine/samples/voxel-shape-collisions/main.cpp
engine/src/collisions/interface/colliding_with.cpp
engine/src/collisions/interface/contact_manifold.cpp
engine/src/collisions/interface/plugin.cpp
engine/src/collisions/narrow_phase/plugin.cpp
engine/src/collisions/plugin.cpp
engine/src/physics/constraints/penetration_constraint.cpp
engine/src/physics/constraints/penetration_constraint.hpp
engine/src/physics/solver/penetration_constraint/plugin.cpp

Remove everything from CollidingWith except entity, add a vector of manifolds.
ContactManifold is no longer a relation.
Same thing for PenetrationConstraint, add a PenetrationtConstraints relation that holds a vector of PenetrationConstraint.
Change narrow phase systems to buildup the vector of manifolds in a collidingWith relation.
Change peneration constraint plugin to create the vector of PenetrationConstraint for each manifold.
Change penetraton constraint solver to buildup the effects of all constraints in PenetrationConstraints

feat(engine): allow multiple contacts between two entities

---

CHANGELOG.md
engine/CMakeLists.txt
engine/include/cubos/engine/collisions/collider.hpp
engine/include/cubos/engine/collisions/collision_layers.hpp
engine/include/cubos/engine/collisions/collision_mask.hpp
engine/include/cubos/engine/collisions/plugin.hpp
engine/include/cubos/engine/collisions/raycast.hpp
engine/samples/collisions/main.cpp
engine/samples/complex_physics/assets/scenes/red_cube.cubos
engine/samples/complex_physics/assets/scenes/white_cube.cubos
engine/samples/complex_physics/main.cpp
engine/src/collisions/broad_phase/collision_group.cpp
engine/src/collisions/broad_phase/collision_group.hpp
engine/src/collisions/broad_phase/plugin.cpp
engine/src/collisions/interface/collider.cpp
engine/src/collisions/interface/collision_layers.cpp
engine/src/collisions/interface/collision_mask.cpp
engine/src/collisions/interface/plugin.cpp
engine/src/collisions/interface/raycast.cpp
engine/tests/raycast.cpp

Move collision layers and masks to their own components and create `CollisionGroup` component. Check out the issue for more info.
Currently collisions are detected if either of the bodies detects the other (this functionality will be extended in future PRs).

Add collision masks and layers

---

CHANGELOG.md
engine/assets/render/g_buffer_rasterizer.fs
engine/assets/render/g_buffer_rasterizer.vs
engine/include/cubos/engine/render/defaults/target.hpp
engine/src/gizmos/plugin.cpp
engine/src/render/defaults/plugin.cpp
engine/src/render/defaults/target.cpp
engine/src/render/g_buffer_rasterizer/plugin.cpp

Allows the renderer to work without RenderPicker, for a performance boost. If the RenderPicker component isn't present in the render target, the feature is disabled.

Make RenderPicker optional

---

flake.nix

Cubos was not able to run on wayland with the nix flake because of mismatching wayland versions being used by the graphics.
The solution was to include the wayland library used by the system in the library path.

chore: added support for wayland in flake.nix

---

CHANGELOG.md
core/include/cubos/core/geom/frustum.hpp
core/include/cubos/core/geom/intersections.hpp
core/src/geom/intersections.cpp
engine/CMakeLists.txt
engine/include/cubos/engine/render/camera/camera.hpp
engine/src/render/camera/camera.cpp
engine/src/render/camera/plugin.cpp
engine/src/render/g_buffer_rasterizer/plugin.cpp

Added frustum culling for Perspective and Orthographic camera, avoiding submitting draw calls for meshes outside the camera vision.

feat(rendering): add frustum culling for voxel meshes

---

CHANGELOG.md
engine/include/cubos/engine/font/font.hpp
engine/samples/CMakeLists.txt
engine/samples/imgui/main.cpp
engine/src/font/font.cpp
engine/src/imgui/imgui.cpp
engine/src/imgui/imgui.hpp
engine/src/imgui/plugin.cpp
tools/tesseratos/src/tesseratos/main.cpp

This PR changes the ImGui style to use Roboto as a font and also the colors of the menus to match the brand guidelines.

Use custom ImGui style and font

---

CHANGELOG.md
engine/include/cubos/engine/gizmos/target.hpp
engine/src/gizmos/plugin.cpp
engine/src/gizmos/renderer.cpp
engine/src/tools/selection/plugin.cpp

- The bug in the issue came from considering `ImGui::GetWindowSize()` to return the window size - it doesn't, it returns the current ImGui window's size. I simply replaced it by the correct call.
- I also noticed that when I clicked, depth wasn't properly taken into account, i.e., occluded gizmos were sometimes selected instead of the ones in front. Turns out we forgot to bind the depth texture on the gizmos framebuffer.

Make selection gizmos clickable again and properly handle their depth

---

.github/workflows/preview-docs.yml
CHANGELOG.md
engine/src/tools/console/plugin.cpp

Added an auto-scroll toggle to Console tool, so the user does not need to scroll manually.

1438 add auto-scroll toggle to Console tool

---

CHANGELOG.md
core/CMakeLists.txt
core/include/cubos/core/data/transparent/string_equal.hpp
core/include/cubos/core/data/transparent/string_hash.hpp
core/include/cubos/core/reflection/external/unordered_map.hpp
core/src/data/transparent/string_equal.cpp
core/src/data/transparent/string_hash.cpp
engine/include/cubos/engine/input/bindings.hpp
engine/include/cubos/engine/input/input.hpp
engine/src/input/bindings.cpp
engine/src/input/input.cpp

Change the name parameter type in input methods like ::pressed, ::axis, etc., to use std::string_view for more readable usage

1437 change inputpressed axis etc to use stdstring_view

---

engine/include/cubos/engine/collisions/shapes/voxel.hpp
engine/src/physics/components/inertia.cpp

GCC 15 seems to have broken something in the inertia.cpp code. This change seems to fix the compile error just want to be sure it doesn't modify the expected behaviour.
[compile error.txt](https://github.com/user-attachments/files/20002752/out.txt)

fix(build): compile error in inertia.cpp when using gcc 15

---

CHANGELOG.md
engine/samples/CMakeLists.txt
engine/samples/emscripten.html

Added an emscripten template for the engine samples, so that they're pretty on the browser.

feat(engine): add Emscripten HTML template for samples

---

CHANGELOG.md
engine/src/imgui/inspector.cpp

Adds a toggle to the ImGui inspector for 4x4 matrices which allows enabling and disabling decomposition into the translation, rotation, etc, components.
To test this functionality you can run the engine-sample.imgui sample, open 'State (Edit)' (or show), scroll down, and open the glm header.

feat(imgui): toggle for matrix decomposition on inspector

---

CHANGELOG.md
engine/include/cubos/engine/gizmos/gizmos.hpp
engine/samples/collisions/main.cpp
engine/samples/gizmos/main.cpp
engine/samples/voxel-shape-collisions/main.cpp
engine/src/gizmos/gizmos.cpp
engine/src/gizmos/plugin.cpp
engine/src/gizmos/types/box.hpp
engine/src/gizmos/types/cut_cone.hpp
engine/src/gizmos/types/line.hpp
engine/src/gizmos/types/ring.hpp
engine/src/tools/transform_gizmo/plugin.cpp

Adds an option to specify which cameras to draw a gizmo for.
Also fixes other gizmos-related bugs.

Allow gizmos to be drawn for specific cameras

---

CHANGELOG.md
core/include/cubos/core/ecs/cubos.hpp
core/src/ecs/cubos.cpp
engine/src/transform/plugin.cpp

Added a named method that allows to attribute a name to the current plugin. 
This feature is especially useful for scripting, because we can import a plugin by it's name at runtime.

feat(core): added named plugins

---

CHANGELOG.md
engine/src/imgui/inspector.cpp

Adds a popup to quaternions on the inspector which allows the user to select between three representation modes:
- raw (e.g., just show the 4 quaternion fields as is);
- euler angles XYZ (yaw, pitch, row)
- axis (vec3) + angle
Additionally, the user can toggle between degrees and radians.
To test this functionality you can run the `engine-sample.imgui` sample, open 'State (Edit)' (or show), scroll down, and open the glm header.

feat(imgui): allow changing quaternion mode on inspector

---

CHANGELOG.md
bindings/lua/CMakeLists.txt
bindings/lua/samples/CMakeLists.txt
bindings/lua/samples/systems/main.cpp
bindings/lua/samples/systems/scripts/test.lua
bindings/lua/src/cubos.cpp
bindings/lua/src/cubos.hpp
bindings/lua/src/plugin.cpp
bindings/lua/src/systems.cpp
bindings/lua/src/systems.hpp
core/include/cubos/core/ecs/cubos.hpp
core/src/ecs/cubos.cpp

Add `cubos.system` and `cubos.startupSystem` functions to lua bindings, currently without any system args

feat(scripting): add system and startupsystem to lua

---

CHANGELOG.md
tools/quadrados/CMakeLists.txt
tools/quadrados/src/import.cpp
tools/quadrados/src/tools.hpp

Adds a simple tool to the quadrados project to generate .meta files with random UUIDs automatically. This solves the current problem where users have to manually generate UUIDs through external programs or websites and write .meta files by hand. With this tool, running quadrados import dir/asset.qb will create asset.qb.meta with a proper UUID, streamlining the asset import process.
Output:
{
"id": "1fiekvrd-v360-d5p5-xssz-0i3al2f2zl6k"
}
- [ x] Self-review changes.

feat: Allow generating metas with random UUIDs through Quadrados

---

bindings/lua/CMakeLists.txt
bindings/lua/samples/hello_world/scripts/hello.lua
bindings/lua/src/cubos.cpp
bindings/lua/src/logging.cpp
bindings/lua/src/logging.hpp

feat(scripting): added logging functions
